// Phụ lục 3, 4 – bản rút gọn theo mẫu Khoa; cấu trúc 15 bài (đã gộp Bài 6 – Bài 7 cũ)
const R = {
  VL1: "Cao Bích Thủy (2016), Các phương thức điều trị Vật lý trị liệu I. Trường Đại học Kỹ thuật Y - Dược Đà Nẵng. Lưu hành nội bộ.",
  VL2: "Lê Quang Khanh (2016), Các phương thức điều trị Vật lý trị liệu II. Trường Đại học Kỹ thuật Y - Dược Đà Nẵng. Lưu hành nội bộ.",
  PNF: "Lê Quang Khanh (2018), Giáo trình Tạo thuận thần kinh cơ cảm thụ bản thể. Trường Đại học Kỹ thuật Y - Dược Đà Nẵng. Lưu hành nội bộ.",
  TK1: "Lê Khánh Điền, Nguyễn Thi Hương (2008), Kỹ thuật tạo thuận cảm thụ bản thể thần kinh cơ. Nhà xuất bản Y học, Hà Nội.",
  TK2: "Adler S.S., Beckers D., Buck M. (2014), PNF in Practice, 4th ed. Springer-Verlag Berlin Heidelberg.",
  TKH: "Nguyễn Thị Hạnh (2024), Bài giảng Bệnh lý và vật lý trị liệu hệ thần kinh cơ nâng cao. Trường Đại học Kỹ thuật Y - Dược Đà Nẵng. Lưu hành nội bộ.",
};
const elec = "Sinh viên đọc kỹ giáo trình Các phương thức điều trị Vật lý trị liệu I, mục tiêu bài học và các yêu cầu thực hành. Trước khi học, sinh viên cần nắm:";
const soft = "Sinh viên đọc kỹ giáo trình Các phương thức điều trị Vật lý trị liệu II, mục tiêu bài học và các yêu cầu thực hành. Trước khi học, sinh viên cần nắm:";
const pnf = "Sinh viên đọc kỹ Giáo trình Tạo thuận thần kinh cơ cảm thụ bản thể, mục tiêu bài học và các yêu cầu thực hành. Trước khi học, sinh viên cần nắm:";
const svDefault = (n) => [`Đọc trước tài liệu bài học và Phụ lục hướng dẫn tự học Bài ${n} trên E-learning.`];
const postDefault = ["Làm bài quiz ngắn (5 câu) trên hệ thống E-learning trước buổi học kế tiếp.", "Gửi câu hỏi thắc mắc vào diễn đàn lớp học trên E-learning."];
const PNF_LLO = (v) => [
  "Trình bày được các tiến trình cơ bản cho một mẫu vận động.",
  `Trình bày được kỹ thuật thao tác cho các mẫu ở ${v}.`,
  `Thực hiện đúng kỹ thuật thao tác các mẫu vận động ở ${v}.`,
  `Lựa chọn được mẫu và kỹ thuật PNF phù hợp cho trường hợp điều trị cụ thể ở ${v}.`,
  "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
  `Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các mẫu PNF của ${v} trên mô hình hoặc tình huống lâm sàng giả định.`,
];

module.exports = [
  // ===================== BÀI 1 =====================
  {
    title: "Năng lượng bức xạ, các định luật và điều trị bằng tia", lt: 1, part: "A",
    summary: "Bài học cung cấp kiến thức nền tảng về bản chất sóng điện từ, các quá trình phản chiếu, khúc xạ, hấp thu và các định luật chi phối liều chiếu (định luật Grotthus – Draper, định luật nghịch đảo bình phương khoảng cách, định luật cosin). Trên cơ sở đó, sinh viên tìm hiểu tia hồng ngoại: nguồn phát xạ, tác dụng sinh lý, tác dụng điều trị, chỉ định, chống chỉ định, tai biến và quy trình kỹ thuật chiếu. Đây là nền tảng để sinh viên lý giải cơ chế của các phương thức vật lý dùng năng lượng bức xạ và thực hiện an toàn kỹ thuật chiếu hồng ngoại trên người bệnh.",
    prepIntro: elec,
    prep: [
      "Kiến thức Lý sinh về sóng điện từ: bước sóng, tần số, năng lượng; phổ điện từ.",
      "Các quá trình phản chiếu, khúc xạ, hấp thu khi bức xạ tác động lên mô.",
      "Nội dung và ý nghĩa thực hành của định luật Grotthus – Draper, định luật nghịch đảo bình phương khoảng cách và định luật cosin.",
      "Sinh lý điều nhiệt, phản ứng giãn mạch của da khi tăng nhiệt.",
      "Tác dụng sinh lý, tác dụng điều trị, chỉ định, chống chỉ định và tai biến của tia hồng ngoại.",
      "Các bước của quy trình kỹ thuật chiếu đèn hồng ngoại.",
    ],
    reallife: "Sinh viên quan sát việc sử dụng đèn hồng ngoại tại gia đình hoặc cơ sở y tế và nhận xét những sai sót có thể gây bỏng.",
    think: [
      "Đèn hồng ngoại được đặt cách da 30 cm thay vì 50–75 cm.",
      "Người bệnh đái tháo đường giảm cảm giác bàn chân được chỉ định chiếu hồng ngoại vùng gót.",
      "Đèn chiếu xiên một góc lớn so với bề mặt vùng điều trị.",
    ],
    refs: [R.VL1],
    terms: "Sóng điện từ; Bước sóng; Phản chiếu; Khúc xạ; Hấp thu; Định luật Grotthus – Draper; Định luật nghịch đảo bình phương khoảng cách; Định luật cosin; Tia hồng ngoại (IR); Ban đỏ do nhiệt",
    questions: [
      "Trình bày các quá trình phản chiếu, khúc xạ, hấp thu và ý nghĩa đối với liều điều trị.",
      "Khi tăng khoảng cách đèn – da lên gấp đôi, cường độ bức xạ tới da thay đổi như thế nào? Giải thích.",
      "Phân tích tác dụng sinh lý của tia hồng ngoại và liên hệ với các chỉ định điều trị.",
      "Kể các chống chỉ định và tai biến của chiếu hồng ngoại; nêu biện pháp đề phòng.",
      "Những bước nào trong quy trình chiếu hồng ngoại quyết định an toàn cho người bệnh?",
    ],
    cases: [
      { text: "Nam 45 tuổi, nhân viên văn phòng, đau mỏi vùng cổ vai hai bên 3 tháng, đau tăng cuối ngày. Khám: co cứng cơ thang trên hai bên, da vùng cổ vai bình thường, cảm giác nóng – lạnh bình thường, không sốt. Bác sĩ chỉ định chiếu đèn hồng ngoại vùng cổ vai.",
        tasks: ["Phân tích cơ sở lựa chọn tia hồng ngoại cho người bệnh.", "Liệt kê các nội dung cần kiểm tra trước khi chiếu.", "Đề xuất khoảng cách, góc chiếu, thời gian chiếu và giải thích dựa trên các định luật đã học.", "Nêu cách xử trí nếu người bệnh than nóng rát trong khi chiếu."] },
    ],
    llo: [
      "Mô tả được sự phát sinh, đặc tính sóng của điện từ và các quá trình phản chiếu, khúc xạ, hấp thu.",
      "Phân tích được nguồn phát xạ, tác dụng sinh lý, tác dụng điều trị, ứng dụng lâm sàng, chống chỉ định và tai biến của tia hồng ngoại.",
      "Thực hiện đúng kỹ thuật điều trị bằng tia hồng ngoại trên người bệnh giả định theo quy trình.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành kỹ thuật điều trị bằng tia hồng ngoại trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu nội dung bài học (phổ điện từ, sơ đồ các định luật).", "Chuẩn bị câu hỏi động não và bài tập tính cường độ theo khoảng cách.", "Chuẩn bị hình ảnh/video quy trình chiếu đèn hồng ngoại và các tai biến bỏng.", "Thiết lập bộ câu hỏi lượng giá nhanh (Kahoot/Quizizz)."],
    sv: ["Suy nghĩ về các ứng dụng thực tế (đặc biệt nguy cơ bỏng khi đặt đèn sai khoảng cách)."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, đèn hồng ngoại (hoặc hình ảnh).",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: “Đèn hồng ngoại được dùng ở đâu? Cảm giác khi chiếu?”", "Giới thiệu LLO của bài học."], 5],
      ["2. Sóng điện từ và các định luật", ["Thuyết giảng tích cực: sự phát sinh, đặc tính sóng điện từ; phản chiếu, khúc xạ, hấp thu.", "Think–Pair–Share (2 phút): dự đoán cường độ tới da khi tăng khoảng cách đèn từ 50 cm lên 100 cm; giảng viên chốt định luật nghịch đảo bình phương và định luật cosin."], 15],
      ["3. Tia hồng ngoại", ["Thuyết giảng: nguồn phát xạ, độ xuyên sâu, tác dụng sinh lý và điều trị, chỉ định.", "Câu hỏi động não: “Nhiệt tác động lên mô như thế nào?” → hệ thống hóa thành sơ đồ."], 12],
      ["4. Chống chỉ định, tai biến và quy trình kỹ thuật", ["Trình chiếu hình ảnh tai biến bỏng; phân tích nguyên nhân.", "Giới thiệu quy trình chiếu và các bước trọng yếu sẽ được đánh giá ở TH1."], 10],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt từ khóa cốt lõi.", "Lượng giá nhanh: 3–4 câu MCQ trên Kahoot/Slido.", "Dặn dò ôn quy trình để thực hành."], 8],
    ],
    post: postDefault,
  },

  // ===================== BÀI 2 =====================
  {
    title: "Điều trị bằng sóng", lt: 5, part: "A",
    summary: "Bài học trình bày bốn phương thức điều trị bằng sóng thường dùng trong Vật lý trị liệu: dòng cao tần và thấu nhiệt sóng ngắn, laser công suất thấp, sóng xung kích và siêu âm điều trị. Với mỗi phương thức, sinh viên tìm hiểu nguyên lý vật lý, tác dụng nhiệt và không nhiệt, thông số điều trị, chỉ định, chống chỉ định, tai biến, cách chuẩn bị máy và người bệnh, biện pháp bảo đảm an toàn. Bài học giúp sinh viên so sánh độ xuyên sâu và tác dụng của từng loại sóng để lựa chọn phương thức phù hợp với vị trí tổn thương, giai đoạn bệnh và đáp ứng của người bệnh, đồng thời vận hành máy đúng quy trình, an toàn.",
    prepIntro: elec,
    prep: [
      "Phân biệt sóng điện từ (sóng ngắn, laser) và sóng cơ học (siêu âm, sóng xung kích); tác dụng nhiệt và không nhiệt.",
      "Sóng ngắn: tần số 27,12 MHz, phương pháp điện dung và cảm ứng, chế độ liên tục và xung, liều theo cảm giác người bệnh.",
      "Laser: đặc tính đơn sắc, kết hợp, định hướng; mật độ năng lượng (J/cm²); an toàn mắt.",
      "Sóng xung kích: dạng hội tụ và tỏa tia; các thông số áp lực, số xung, tần số.",
      "Siêu âm: tần số 1 MHz và 3 MHz với độ sâu tương ứng; chu kỳ xung; cường độ; ERA, BNR; chất tiếp âm.",
      "Chỉ định, chống chỉ định, tai biến và biện pháp an toàn của từng phương thức.",
    ],
    reallife: "Sinh viên tìm hiểu các loại máy sóng đang sử dụng tại khoa Phục hồi chức năng của cơ sở thực hành và các quy định an toàn tại phòng máy.",
    think: [
      "Người bệnh đau thắt lưng có nẹp vít cột sống được đề nghị điều trị sóng ngắn vùng thắt lưng.",
      "Viêm gân trên gai giai đoạn bán cấp: nên chọn siêu âm 1 MHz hay 3 MHz, liên tục hay xung?",
      "Người bệnh có máy tạo nhịp tim cần điều trị đau khớp gối.",
    ],
    refs: [R.VL1],
    terms: "Thấu nhiệt sóng ngắn (SWD); Phương pháp điện dung; Phương pháp cảm ứng; Laser công suất thấp (LLLT); Mật độ năng lượng (J/cm²); Sóng xung kích (ESWT); Siêu âm điều trị; Chu kỳ xung (duty cycle); Diện tích bức xạ hiệu dụng (ERA); Tỉ số không đồng đều chùm tia (BNR); Chất tiếp âm",
    questions: [
      "So sánh phương pháp điện dung và cảm ứng của sóng ngắn về cách đặt điện cực và loại mô được làm nóng.",
      "Nêu các biện pháp bảo đảm an toàn cho người bệnh, người vận hành và máy khi điều trị sóng ngắn.",
      "Máy laser 50 mW chiếu trên 1 cm² trong 60 giây: tính mật độ năng lượng.",
      "Phân tích căn cứ chọn tần số và chế độ phát của siêu âm theo độ sâu và giai đoạn tổn thương.",
      "Trình bày chỉ định, chống chỉ định và tai biến của sóng xung kích.",
      "Lập bảng so sánh 4 phương thức: bản chất sóng, độ xuyên sâu, tác dụng chính, chống chỉ định đặc thù.",
    ],
    cases: [
      { text: "Nữ 52 tuổi, đau gót chân phải 8 tháng, đau nhất ở những bước đầu buổi sáng; chẩn đoán viêm cân gan chân mạn tính, đã dùng thuốc và lót gót nhưng ít cải thiện. Tiền sử tăng huyết áp ổn định, không dùng thuốc chống đông, không có thai, không có kim loại cấy ghép.",
        tasks: ["Đề xuất phương thức điều trị bằng sóng phù hợp nhất và giải thích cơ chế.", "Nêu các thông số cần thiết lập và các bước chuẩn bị máy, người bệnh.", "Nếu người bệnh đang dùng thuốc chống đông, lựa chọn thay đổi thế nào?"] },
      { text: "Nam 40 tuổi, viêm gân trên gai phải giai đoạn bán cấp, đau khi dạng vai 60°–120°; không có kim loại, không có bệnh lý ác tính.",
        tasks: ["Lựa chọn phương thức sóng phù hợp.", "Đề xuất tần số, chế độ phát, cường độ, thời gian và giải thích.", "Nêu các lưu ý an toàn trong quá trình điều trị."] },
    ],
    llo: [
      "Phân tích được đại cương, ứng dụng điều trị, chỉ định, chống chỉ định, tai biến và các biện pháp đề phòng của sóng ngắn, laser, sóng xung kích, siêu âm.",
      "Thực hiện đúng kỹ thuật điều trị bằng sóng, bao gồm chuẩn bị máy và người bệnh, bảo đảm an toàn cho người bệnh và máy.",
      "Lựa chọn được kỹ thuật điều trị bằng sóng phù hợp với chỉ định và đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các kỹ thuật điều trị bằng sóng trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu cho 2 buổi học.", "Chuẩn bị hình ảnh/video cách đặt điện cực sóng ngắn, kỹ thuật di chuyển đầu siêu âm, đầu phát sóng xung kích.", "Chuẩn bị 3–4 tình huống lâm sàng ngắn cho thảo luận nhóm.", "Thiết lập bộ câu hỏi lượng giá nhanh (Kahoot/Quizizz)."],
    sv: ["Lập bảng so sánh 4 phương thức (bản nháp) trước buổi học.", "Suy nghĩ về các ứng dụng thực tế (đặc biệt các chống chỉ định: kim loại, máy tạo nhịp, thai, mắt)."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu; đầu phát siêu âm, điện cực sóng ngắn, kính bảo hộ laser (vật thật hoặc hình ảnh).",
    acts: [
      { section: "Buổi 1 (03 tiết – 150 phút)" },
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kiểm tra chuẩn bị bài: 5 câu hỏi nhanh từ Phụ lục 3.", "Giới thiệu LLO của bài học."], 10],
      ["2. Đại cương các phương thức dùng sóng", ["Thuyết giảng tích cực: phân loại sóng điện từ và sóng cơ học; tác dụng nhiệt và không nhiệt.", "Câu hỏi gợi mở: “Vì sao sóng ngắn làm nóng sâu hơn hồng ngoại?”"], 15],
      ["3. Dòng cao tần và thấu nhiệt sóng ngắn", ["Thuyết giảng: nguyên lý tạo nhiệt; phương pháp điện dung/cảm ứng; liên tục/xung; liều.", "Chỉ định, chống chỉ định, tai biến; an toàn cho người bệnh, người vận hành và máy.", "Thảo luận nhóm đôi (2 phút): vì sao phải tháo bỏ kim loại, lau khô mồ hôi, không để dây cáp chạm nhau?"], 40],
      ["4. Siêu âm điều trị", ["Thuyết giảng: tần số và độ sâu; liên tục/xung; cường độ; ERA, BNR; chất tiếp âm; kỹ thuật di chuyển đầu phát; điều trị dưới nước.", "Video: kỹ thuật di chuyển đầu phát đúng/sai.", "Chỉ định, chống chỉ định, tai biến."], 45],
      ["5. Dạy học dựa trên tình huống (CBL)", ["Nhóm 4–6 sinh viên phân tích 2 tình huống: đau thắt lưng có nẹp vít cột sống; viêm gân trên gai bán cấp.", "Đại diện nhóm trình bày; giảng viên phản hồi."], 30],
      ["6. Tổng kết", ["Tóm tắt; so sánh sóng ngắn – siêu âm.", "Dặn dò đọc phần Laser, Sóng xung kích."], 10],
      { section: "Buổi 2 (02 tiết – 100 phút)" },
      ["1. Mở đầu", ["Câu hỏi gợi mở ôn lại buổi 1; giới thiệu LLO buổi 2."], 5],
      ["2. Laser trong Vật lý trị liệu", ["Thuyết giảng tích cực: đặc tính laser, cơ chế quang sinh học, liều (J/cm²).", "Bài tập nhóm đôi: tính mật độ năng lượng.", "Chỉ định, chống chỉ định, an toàn mắt."], 30],
      ["3. Sóng xung kích", ["Thuyết giảng: sóng hội tụ và tỏa tia; thông số; cơ chế.", "Hình ảnh lâm sàng: viêm cân gan chân, bệnh lý gân vôi hóa.", "Chỉ định, chống chỉ định, tai biến."], 25],
      ["4. Dạy học dựa trên tình huống (CBL)", ["Ca lâm sàng: viêm cân gan chân mạn tính; biến thể người bệnh dùng thuốc chống đông, người bệnh có máy tạo nhịp.", "Nhóm đề xuất phương thức, thông số, biện pháp an toàn; giảng viên chốt."], 30],
      ["5. Tổng kết và Lượng giá tại lớp", ["Bảng tổng hợp 4 phương thức.", "Lượng giá nhanh: 3–5 câu MCQ trên Kahoot/Slido.", "Dặn dò chuẩn bị thực hành."], 10],
    ],
    post: postDefault,
  },

  // ===================== BÀI 3 =====================
  {
    title: "Các dòng điện xung", lt: 3, part: "A",
    summary: "Bài học trình bày khái niệm kích thích điện, cơ sở sinh lý của đáp ứng thần kinh – cơ với dòng điện (ngưỡng kích thích, đường cong cường độ – thời gian, lưu huyết, thời trị) và các thông số của dòng điện xung. Sinh viên tìm hiểu kích thích điện thần kinh – cơ, các dòng điện giảm đau (TENS, dòng giao thoa, dòng diadynamic, dòng một chiều đều), nguyên tắc lựa chọn dòng điện, xác định điểm vận động và vị trí đặt điện cực, kỹ thuật điều trị bằng điện cực điểm và điện cực tấm. Bài học giúp sinh viên lý giải cơ chế, lựa chọn dòng điện phù hợp với mục tiêu điều trị và thực hiện kỹ thuật an toàn.",
    prepIntro: elec,
    prep: [
      "Sinh lý điện thế màng nghỉ, điện thế hoạt động và dẫn truyền thần kinh – cơ.",
      "Các thông số của dòng xung: dạng xung, độ rộng xung, tần số, cường độ, thời gian bật/tắt.",
      "Đường cong cường độ – thời gian; lưu huyết; thời trị; khác biệt giữa cơ còn và mất thần kinh chi phối.",
      "Các dòng giảm đau: TENS (thông thường, kiểu châm cứu), dòng giao thoa, dòng diadynamic; cơ chế cổng kiểm soát và opioid nội sinh.",
      "Điểm vận động của các cơ lớn; nguyên tắc mật độ dòng điện và khoảng cách điện cực.",
      "Chống chỉ định và các vị trí không được đặt điện cực.",
    ],
    reallife: "Sinh viên tìm hiểu các máy TENS cầm tay đang bán trên thị trường và phân tích nguy cơ khi người bệnh tự sử dụng không có hướng dẫn.",
    think: [
      "Người bệnh đau thắt lưng cấp sau bê vật nặng, VAS 7/10.",
      "Người bệnh yếu cơ tứ đầu sau mổ tái tạo dây chằng chéo trước 2 tuần.",
      "Điện cực được đặt ở vùng trước cổ để giảm đau cơ ức đòn chũm.",
    ],
    refs: [R.VL1],
    terms: "Kích thích điện thần kinh – cơ (NMES); Kích thích điện thần kinh qua da (TENS); Dòng giao thoa (IFC); Dòng diadynamic; Độ rộng xung; Lưu huyết (rheobase); Thời trị (chronaxie); Đường cong cường độ – thời gian; Điểm vận động; Mật độ dòng điện; Điện cực điểm; Điện cực tấm",
    questions: [
      "Giải thích đường cong cường độ – thời gian và ứng dụng trong chẩn đoán, điều trị cơ mất thần kinh chi phối.",
      "So sánh TENS thông thường và TENS kiểu châm cứu về thông số và cơ chế giảm đau.",
      "Trình bày nguyên tắc lựa chọn dòng điện theo mục tiêu: giảm đau, tăng sức cơ, giảm phù nề.",
      "Kích thước và khoảng cách điện cực ảnh hưởng thế nào đến mật độ dòng và độ sâu tác động?",
      "Kể các chống chỉ định và vị trí không được đặt điện cực.",
    ],
    cases: [
      { text: "Nam 38 tuổi, đau thắt lưng cấp 3 ngày sau bê vật nặng, đau tại chỗ, không lan xuống chân, không rối loạn cơ tròn; VAS 7/10; co cứng cơ cạnh sống. Không có máy tạo nhịp, không bệnh lý tim mạch, da vùng thắt lưng lành lặn.",
        tasks: ["Đề xuất dòng điện giảm đau phù hợp và giải thích cơ chế.", "Xác định thông số và vị trí đặt điện cực.", "Nêu các bước kiểm tra an toàn và theo dõi đáp ứng trong khi điều trị."] },
      { text: "Nữ 25 tuổi, sau mổ tái tạo dây chằng chéo trước gối phải 2 tuần; co cơ tứ đầu chủ động yếu, mất duỗi gối chủ động cuối tầm.",
        tasks: ["Lựa chọn loại dòng điện để tăng huy động cơ tứ đầu.", "Đề xuất vị trí điện cực và thông số (tần số, độ rộng xung, thời gian bật/tắt).", "Nêu cách phối hợp kích thích điện với co cơ chủ động."] },
    ],
    llo: [
      "Phân tích được khái niệm kích thích điện, các dòng điện kích thích thần kinh – cơ và các dòng điện giảm đau.",
      "Thực hiện đúng kỹ thuật điều trị bằng điện cực điểm và bằng điện cực tấm.",
      "Lựa chọn được dòng điện và vị trí đặt điện cực phù hợp với chỉ định và đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các kỹ thuật điều trị bằng dòng điện xung trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu (đồ thị dạng xung, đường cong I/t, bản đồ điểm vận động).", "Chuẩn bị máy điện xung/TENS để minh họa trên sinh viên tình nguyện.", "Chuẩn bị 2 tình huống lâm sàng và phiếu lựa chọn dòng điện.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Suy nghĩ về các ứng dụng thực tế (đặc biệt nguy cơ khi tự sử dụng máy TENS tại nhà)."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu; máy điện xung/TENS, điện cực điểm và điện cực tấm.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Minh họa: giảng viên áp TENS trên một sinh viên tình nguyện, tăng dần cường độ từ cảm giác đến co cơ; đặt câu hỏi “điều gì xảy ra?”", "Giới thiệu LLO của bài học."], 10],
      ["2. Kích thích điện và cơ sở sinh lý", ["Thuyết giảng tích cực: ngưỡng kích thích, đường cong I/t, lưu huyết, thời trị; thông số dòng xung; điểm vận động.", "Thảo luận nhóm đôi (2 phút): so sánh đường cong I/t của cơ bình thường và cơ mất thần kinh."], 30],
      ["3. Kích thích điện thần kinh – cơ", ["Thuyết giảng: NMES, kích thích cơ còn và mất thần kinh chi phối; chọn thông số tăng sức cơ, chống teo cơ."], 25],
      ["4. Các dòng điện giảm đau", ["Thuyết giảng: TENS, dòng giao thoa, dòng diadynamic, dòng một chiều đều và điện di thuốc.", "Câu hỏi động não: ghép từng loại dòng với cơ chế giảm đau."], 35],
      ["5. Lựa chọn dòng điện và vị trí điện cực", ["Nguyên tắc chọn dòng; điện cực điểm/điện cực tấm; mật độ dòng; chống chỉ định và an toàn.", "Dạy học dựa trên tình huống (CBL): nhóm điền phiếu lựa chọn dòng điện cho 2 tình huống; đại diện trình bày."], 40],
      ["6. Tổng kết và Lượng giá tại lớp", ["Tóm tắt từ khóa cốt lõi.", "Lượng giá nhanh: 3–5 câu MCQ trên Kahoot/Slido.", "Dặn dò chuẩn bị bản đồ điểm vận động cho buổi thực hành."], 10],
    ],
    post: postDefault,
  },

  // ===================== BÀI 4 =====================
  {
    title: "Máy kéo cột sống", lt: 1, part: "A",
    summary: "Bài học giới thiệu các loại máy kéo cột sống (kéo cổ, kéo thắt lưng; kéo liên tục và ngắt quãng; tư thế nằm và ngồi), nguyên lý cơ học và tác dụng của lực kéo: tách các thân đốt sống, mở rộng lỗ liên hợp, giảm áp lực đĩa đệm, kéo giãn phần mềm và giảm co thắt cơ. Sinh viên phân tích chỉ định, chống chỉ định, nguyên tắc chọn lực kéo, góc kéo, thời gian, chế độ kéo và các biện pháp bảo đảm an toàn cho người bệnh. Bài học giúp sinh viên lựa chọn thông số kéo phù hợp với vị trí tổn thương, tình trạng và đáp ứng của người bệnh.",
    prepIntro: elec,
    prep: [
      "Giải phẫu cột sống cổ và thắt lưng: thân đốt, đĩa đệm, lỗ liên hợp, rễ thần kinh.",
      "Cơ chế thoát vị đĩa đệm và chèn ép rễ thần kinh.",
      "Các loại máy kéo; kéo liên tục và kéo ngắt quãng.",
      "Nguyên tắc chọn lực kéo theo trọng lượng cơ thể; góc kéo theo tầng tổn thương; thời gian kéo.",
      "Chỉ định, chống chỉ định và các dấu hiệu phải dừng kéo.",
    ],
    reallife: "Sinh viên tìm hiểu các video hướng dẫn “tự kéo cổ tại nhà” trên mạng xã hội và nhận định nguy cơ đối với người bệnh.",
    think: [
      "Người bệnh viêm khớp dạng thấp lâu năm, đau cổ, được đề nghị kéo cổ.",
      "Người bệnh thoát vị đĩa đệm thắt lưng có rối loạn cơ tròn mới xuất hiện.",
      "Người bệnh chóng mặt, buồn nôn ngay sau buổi kéo cổ.",
    ],
    refs: [R.VL1],
    terms: "Kéo cột sống; Kéo liên tục; Kéo ngắt quãng; Lỗ liên hợp; Thoát vị đĩa đệm; Chèn ép rễ thần kinh; Đai chậu; Đai ngực; Góc kéo",
    questions: [
      "Trình bày các tác dụng cơ học và sinh lý của kéo cột sống.",
      "Nêu nguyên tắc chọn lực kéo, góc kéo, chế độ và thời gian kéo cho cột sống cổ và thắt lưng.",
      "Kể các chống chỉ định của kéo cột sống.",
      "Những dấu hiệu nào trong và sau khi kéo cần dừng điều trị và báo bác sĩ?",
    ],
    cases: [
      { text: "Nữ 55 tuổi, đau cổ lan xuống cánh tay trái 4 tuần, tê ngón cái và ngón trỏ; MRI: thoát vị đĩa đệm C5–C6 chèn ép rễ C6 trái. Huyết áp 135/85 mmHg, không chấn thương cổ, không loãng xương. Bác sĩ chỉ định kéo cổ bằng máy.",
        tasks: ["Phân tích cơ sở chỉ định kéo cổ.", "Đề xuất tư thế, góc kéo, lực kéo khởi đầu, chế độ và thời gian kéo.", "Nêu nội dung theo dõi trong buổi kéo và tiêu chí dừng kéo."] },
    ],
    llo: [
      "Phân tích được các loại máy kéo cột sống, nguyên lý, chỉ định và chống chỉ định của kéo cột sống.",
      "Thực hiện đúng nguyên tắc tổng quát và kỹ thuật kéo cột sống, bảo đảm an toàn cho người bệnh.",
      "Lựa chọn được kỹ thuật kéo phù hợp với chỉ định và đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành kỹ thuật kéo cột sống trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu (hình ảnh MRI thoát vị đĩa đệm, các loại máy kéo).", "Chuẩn bị bộ thẻ phân loại chỉ định/chống chỉ định cho hoạt động động não.", "Chuẩn bị 01 tình huống lâm sàng ngắn."],
    sv: ["Suy nghĩ về các ứng dụng thực tế (đặc biệt nguy cơ khi tự kéo cổ không có hướng dẫn)."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu; hình ảnh/video máy kéo cổ – thắt lưng.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: trình chiếu ảnh MRI thoát vị đĩa đệm, hỏi “Lực kéo giúp gì cho người bệnh này?”", "Giới thiệu LLO của bài học."], 5],
      ["2. Các loại máy kéo, nguyên lý và tác dụng", ["Thuyết giảng tích cực: kéo cổ/thắt lưng, liên tục/ngắt quãng; tác dụng cơ học và sinh lý."], 12],
      ["3. Chỉ định, chống chỉ định", ["Động não với bộ thẻ: sinh viên xếp các tình trạng vào nhóm chỉ định/chống chỉ định/thận trọng; giảng viên chốt."], 10],
      ["4. Nguyên tắc và kỹ thuật kéo", ["Thuyết giảng: lực kéo, góc kéo, thời gian, chế độ; theo dõi và tiêu chí dừng kéo.", "CBL nhóm đôi: tình huống thoát vị C5–C6 – đề xuất thông số."], 18],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt; lượng giá nhanh 2–3 câu MCQ.", "Dặn dò chuẩn bị thực hành."], 5],
    ],
    post: postDefault,
  },

  // ===================== BÀI 5 =====================
  {
    title: "Xoa bóp tại chỗ", lt: 2, part: "B",
    summary: "Bài học mở đầu phần kỹ thuật tác động mô mềm, giới thiệu khái niệm xoa bóp tại chỗ, các tác dụng cơ học, phản xạ, tuần hoàn, thần kinh và tâm lý, từ đó dẫn đến tác dụng điều trị: giảm đau, giảm co cứng cơ, tăng hồi lưu tĩnh mạch – bạch huyết, giảm phù nề và tạo thư giãn. Sinh viên phân tích chỉ định, chống chỉ định, nguyên tắc áp dụng và tìm hiểu các thao tác cơ bản: vuốt, xoa (xát), nhào, vỗ – gõ, rung. Bài học giúp sinh viên lựa chọn thao tác phù hợp với tình trạng người bệnh và thực hiện đúng quy trình với sự tôn trọng, giao tiếp phù hợp.",
    prepIntro: soft,
    prep: [
      "Giải phẫu bề mặt và hướng thớ của các nhóm cơ lớn: cơ thang, cơ cạnh sống, cơ tứ đầu, cơ tam đầu cẳng chân.",
      "Sinh lý tuần hoàn tĩnh mạch và bạch huyết.",
      "Tác dụng sinh lý và tác dụng điều trị của xoa bóp.",
      "Chỉ định, chống chỉ định và nguyên tắc áp dụng (tư thế, hướng, lực, nhịp độ, thời gian).",
      "Cách thực hiện và tác dụng chủ yếu của 5 thao tác: vuốt, xoa, nhào, vỗ – gõ, rung.",
    ],
    reallife: "Sinh viên quan sát các hình thức xoa bóp trong cộng đồng (spa, xoa bóp dân gian) và phân biệt với xoa bóp trị liệu về mục tiêu, chỉ định và an toàn.",
    think: [
      "Người bệnh phù nề cổ chân sau tháo bột gãy xương cẳng chân.",
      "Người bệnh sưng, nóng, đau bắp chân một bên 3 ngày sau phẫu thuật.",
      "Vận động viên căng cơ đùi sau thi đấu.",
    ],
    refs: [R.VL2],
    terms: "Xoa bóp trị liệu; Vuốt (effleurage); Xoa – xát (friction); Nhào (petrissage); Vỗ – gõ (tapotement); Rung (vibration); Hồi lưu tĩnh mạch – bạch huyết; Huyết khối tĩnh mạch sâu",
    questions: [
      "Phân tích các tác dụng sinh lý của xoa bóp và liên hệ với tác dụng điều trị.",
      "Trình bày nguyên tắc áp dụng xoa bóp.",
      "So sánh 5 thao tác xoa bóp cơ bản về cách thực hiện và tác dụng chủ yếu.",
      "Vì sao không xoa bóp chi có nghi ngờ huyết khối tĩnh mạch sâu?",
      "Thao tác vuốt nhằm giảm phù nề cần thực hiện theo hướng nào? Giải thích.",
    ],
    cases: [
      { text: "Nữ 30 tuổi, vừa tháo bột cẳng – bàn chân phải sau 6 tuần điều trị gãy kín 1/3 dưới xương chày đã liền xương. Cổ chân và bàn chân phù nhẹ, cơ bắp chân teo và căng, da khô, không có dấu hiệu viêm; siêu âm Doppler đã loại trừ huyết khối tĩnh mạch sâu.",
        tasks: ["Xác định mục tiêu xoa bóp cho người bệnh.", "Lựa chọn thao tác, hướng, lực và trình tự thực hiện; giải thích.", "Nêu các điểm cần chú ý về giao tiếp, tư thế và bảo đảm kín đáo cho người bệnh."] },
    ],
    llo: [
      "Phân tích được tác dụng, chỉ định, chống chỉ định và nguyên tắc áp dụng xoa bóp tại chỗ.",
      "Thực hiện đúng các thao tác xoa bóp cơ bản theo quy trình.",
      "Lựa chọn được thao tác xoa bóp phù hợp với tình trạng và đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành kỹ thuật xoa bóp tại chỗ trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu nội dung bài học.", "Chuẩn bị video các thao tác xoa bóp; khăn, dầu để làm mẫu nhanh.", "Chuẩn bị 01 tình huống lâm sàng cho thảo luận nhóm.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Suy nghĩ về các ứng dụng thực tế (đặc biệt các trường hợp không được xoa bóp)."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa; khăn, dầu xoa bóp.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: giảng viên làm mẫu thao tác vuốt cẳng tay trên một sinh viên, hỏi cảm nhận.", "Giới thiệu LLO của bài học."], 5],
      ["2. Khái niệm, tác dụng sinh lý và điều trị", ["Thuyết giảng tích cực: tác dụng cơ học, phản xạ, tuần hoàn, thần kinh, tâm lý.", "Thảo luận nhóm đôi (2 phút): “Vì sao thao tác vuốt phải theo hướng về tim?”"], 25],
      ["3. Chỉ định, chống chỉ định, nguyên tắc áp dụng", ["Thuyết giảng: chỉ định, chống chỉ định; nguyên tắc tư thế – hướng – lực – nhịp độ – thời gian.", "Câu hỏi động não: các “cờ đỏ” không được xoa bóp."], 20],
      ["4. Các thao tác cơ bản và quy trình", ["Làm mẫu: giảng viên thực hiện nhanh 5 thao tác; sinh viên quan sát và ghi đặc điểm từng thao tác.", "Video quy trình xoa bóp một vùng."], 25],
      ["5. Dạy học dựa trên tình huống (CBL)", ["Ca lâm sàng phù nề cẳng chân sau tháo bột: nhóm xác định mục tiêu, chọn thao tác và trình tự; giảng viên phản hồi."], 15],
      ["6. Tổng kết và Lượng giá tại lớp", ["Tóm tắt; lượng giá nhanh 3 câu MCQ.", "Dặn dò cắt ngắn móng tay, chuẩn bị trang phục thực hành."], 10],
    ],
    post: postDefault,
  },

  // ===================== BÀI 6 (gộp) =====================
  {
    title: "Kỹ thuật tác động điểm kích hoạt: nén, day và trượt dọc theo thớ cơ", lt: 2, part: "B",
    summary: "Bài học trình bày khái niệm điểm kích hoạt – nốt tăng nhạy cảm nằm trong dải cơ căng, khi ấn gây đau tại chỗ và đau quy chiếu đặc trưng; phân biệt điểm kích hoạt hoạt động và tiềm ẩn; cách xác định bằng sờ dẹt và sờ kẹp. Trên cơ sở đó, sinh viên tìm hiểu cơ chế tác dụng, chỉ định, chống chỉ định, tai biến và kỹ thuật của hai nhóm thao tác tác động lên điểm kích hoạt: nén – day điểm kích hoạt và trượt dọc theo thớ cơ ở các nhóm cơ chính. Bài học giúp sinh viên xác định điểm kích hoạt, lựa chọn kỹ thuật phù hợp với đáp ứng của người bệnh và thực hiện an toàn, có giao tiếp và theo dõi người bệnh.",
    prepIntro: soft,
    prep: [
      "Giải phẫu nguyên ủy, bám tận, hướng thớ của cơ thang trên, cơ nâng vai, cơ dưới gai, cơ cạnh sống, cơ mông nhỡ, cơ bụng chân.",
      "Định nghĩa, đặc điểm lâm sàng và tiêu chuẩn xác định điểm kích hoạt; phân biệt điểm kích hoạt hoạt động và tiềm ẩn.",
      "Kiểu đau quy chiếu của cơ thang trên, cơ nâng vai, cơ dưới gai, cơ mông nhỡ.",
      "Cơ chế tác dụng của nén thiếu máu cục bộ và của trượt dọc theo thớ cơ.",
      "Chỉ định, chống chỉ định, tai biến và cách đề phòng.",
      "Quy trình nén – day điểm kích hoạt và quy trình trượt dọc theo thớ cơ.",
    ],
    reallife: "Sinh viên tự sờ tìm dải cơ căng ở cơ thang trên của bản thân hoặc bạn học và ghi lại cảm giác, vùng đau quy chiếu (nếu có).",
    think: [
      "Nhân viên văn phòng đau đầu vùng thái dương, đau tăng khi làm việc máy tính lâu.",
      "Người chạy bộ đau căng bắp chân khi chạy lên dốc.",
      "Người bệnh đang dùng thuốc chống đông có điểm đau ở cơ thang.",
    ],
    refs: [R.VL2],
    terms: "Điểm kích hoạt (trigger point); Dải cơ căng (taut band); Đau quy chiếu; Đáp ứng co giật tại chỗ (LTR); Điểm kích hoạt hoạt động; Điểm kích hoạt tiềm ẩn; Sờ dẹt; Sờ kẹp; Nén thiếu máu cục bộ; Trượt dọc theo thớ cơ (stripping)",
    questions: [
      "Trình bày các đặc điểm giúp xác định một điểm kích hoạt.",
      "Phân tích cơ chế tác dụng của kỹ thuật nén thiếu máu cục bộ.",
      "Mô tả quy trình nén và day điểm kích hoạt (tư thế, lực, thời gian, tiêu chí kết thúc).",
      "So sánh trượt dọc theo thớ cơ với thao tác vuốt về lực, tốc độ và mục tiêu.",
      "Kể các chống chỉ định và tai biến của kỹ thuật tác động điểm kích hoạt.",
      "Vì sao nên kéo dãn cơ sau khi xử lý điểm kích hoạt?",
    ],
    cases: [
      { text: "Nữ 28 tuổi, nhân viên kế toán, đau cổ vai phải và đau đầu vùng thái dương phải 2 tháng, tăng khi làm việc máy tính lâu. Khám: dải cơ căng ở bờ trên cơ thang phải, ấn vào nốt đau tái hiện cơn đau thái dương; nghiêng cổ trái giảm nhẹ; không có dấu hiệu thần kinh khu trú.",
        tasks: ["Xác định cơ có điểm kích hoạt và giải thích mối liên quan với đau đầu.", "Mô tả cách thực hiện nén và day điểm kích hoạt (tư thế, vị trí tay, lực, thời gian).", "Đề xuất hoạt động phối hợp sau kỹ thuật (kéo dãn, hướng dẫn tư thế làm việc)."] },
      { text: "Nam 35 tuổi, chạy bộ 30 km/tuần, đau căng bắp chân trái 3 tuần, đau tăng khi chạy lên dốc. Khám: dải cơ căng ở đầu trong cơ bụng chân trái, không sưng nóng, không giãn tĩnh mạch.",
        tasks: ["Phân tích cơ sở lựa chọn kỹ thuật trượt dọc theo thớ cơ.", "Mô tả tư thế người bệnh, hướng trượt, phần tay sử dụng và lực.", "Nêu các chống chỉ định cần loại trừ trước khi thực hiện."] },
    ],
    llo: [
      "Phân tích được khái niệm, đặc điểm, cách xác định điểm kích hoạt và cơ chế tác dụng, chỉ định, chống chỉ định, tai biến của nén, day điểm kích hoạt và trượt dọc theo thớ cơ.",
      "Thực hiện đúng kỹ thuật nén, day điểm kích hoạt và trượt dọc theo thớ cơ trên các nhóm cơ chính.",
      "Lựa chọn được kỹ thuật phù hợp với đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành nén, day điểm kích hoạt và trượt dọc theo thớ cơ trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu (bản đồ đau quy chiếu các cơ chính, hình ảnh dải cơ căng).", "Chuẩn bị video kỹ thuật sờ dẹt, sờ kẹp, nén – day và trượt dọc theo thớ cơ.", "Chuẩn bị 02 tình huống lâm sàng ngắn.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Suy nghĩ về các ứng dụng thực tế (liên hệ đau cổ vai ở người làm việc văn phòng)."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa; mô hình giải phẫu cơ vùng cổ vai.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: sinh viên tự sờ bờ trên cơ thang, tìm điểm đau và mô tả cảm giác.", "Giới thiệu LLO của bài học."], 5],
      ["2. Điểm kích hoạt: khái niệm, đặc điểm, cách xác định", ["Thuyết giảng tích cực: định nghĩa, phân loại, giả thuyết hình thành; tiêu chuẩn xác định.", "Video: kỹ thuật sờ dẹt, sờ kẹp.", "Câu hỏi động não: nhận diện cơ từ bản đồ đau quy chiếu."], 25],
      ["3. Nén và day điểm kích hoạt", ["Thuyết giảng: cơ chế nén thiếu máu cục bộ; chỉ định, chống chỉ định, tai biến.", "Video & trực quan: quy trình nén – day; giảng viên phân tích lực tay và tiêu chí kết thúc."], 25],
      ["4. Trượt dọc theo thớ cơ", ["Thuyết giảng: cơ chế, chỉ định, chống chỉ định; phân biệt với thao tác vuốt.", "Làm mẫu nhanh trên cơ cạnh sống và cơ bụng chân."], 15],
      ["5. Dạy học dựa trên tình huống (CBL)", ["Nhóm phân tích 2 ca: đau đầu do điểm kích hoạt cơ thang trên; căng cơ bụng chân ở người chạy bộ.", "Nhóm chọn kỹ thuật, mô tả cách thực hiện, đề xuất phối hợp kéo dãn; giảng viên phản hồi."], 20],
      ["6. Tổng kết và Lượng giá tại lớp", ["Tóm tắt từ khóa cốt lõi.", "Lượng giá nhanh: 3–5 câu MCQ trên Kahoot/Slido.", "Dặn dò chuẩn bị trang phục, dầu xoa bóp cho buổi thực hành."], 10],
    ],
    post: postDefault,
  },

  // ===================== BÀI 7 =====================
  {
    title: "Kéo dãn", lt: 2, part: "B",
    summary: "Bài học trình bày kỹ thuật kéo dãn mô mềm nhằm gia tăng chiều dài cơ – gân và tầm vận động khớp. Sinh viên tìm hiểu cơ chế tác dụng dựa trên tính chất đàn hồi – nhớt của mô (biến dạng từ từ, giãn ứng suất), các cơ chế thần kinh (phản xạ căng, ức chế tự sinh, ức chế đối vận) và sự tăng dung nạp kéo dãn; các loại kéo dãn (tĩnh, động, thụ động, chủ động, tự kéo dãn, kéo dãn theo nguyên lý PNF), thông số, chỉ định, chống chỉ định và nguyên tắc an toàn khi kéo dãn các nhóm cơ chính. Bài học là cầu nối giữa phần tác động mô mềm và phần PNF.",
    prepIntro: soft,
    prep: [
      "Sinh lý thần kinh – cơ: suốt cơ, cơ quan gân Golgi, phản xạ căng.",
      "Tính chất đàn hồi – nhớt của mô mềm; khái niệm co rút.",
      "Các loại kéo dãn và thông số (cường độ, thời gian giữ, số lần, tần suất).",
      "Chỉ định, chống chỉ định; nguyên tắc cố định đầu gần, kéo đầu xa.",
      "Tư thế, cố định và hướng kéo dãn của các nhóm cơ: cơ thang trên, cơ ngực lớn, cơ gập háng, cơ tứ đầu, cơ ụ ngồi cẳng chân, cơ tam đầu cẳng chân.",
    ],
    reallife: "Sinh viên quan sát thói quen khởi động – kéo dãn khi tập luyện thể thao và nhận xét các sai lầm thường gặp.",
    think: [
      "Vận động viên kéo dãn bằng động tác nảy mạnh trước khi thi đấu.",
      "Người bệnh hạn chế duỗi gối do co rút sau bất động 6 tuần.",
      "Người bệnh tổn thương tủy cổ dùng hiện tượng tenodesis để cầm nắm.",
    ],
    refs: [R.VL2, "Kisner C., Colby L.A., Borstad J. (2018), Therapeutic Exercise: Foundations and Techniques, 7th ed. F.A. Davis."],
    terms: "Kéo dãn tĩnh; Kéo dãn động; Kéo dãn nảy; Tự kéo dãn; Biến dạng từ từ (creep); Giãn ứng suất (stress relaxation); Phản xạ căng; Ức chế tự sinh; Ức chế đối vận; Co rút",
    questions: [
      "Phân tích cơ chế cơ học và thần kinh của kéo dãn.",
      "So sánh kéo dãn tĩnh, kéo dãn động, kéo dãn nảy và kéo dãn theo nguyên lý PNF.",
      "Trình bày các thông số kéo dãn tĩnh thường dùng ở người lớn.",
      "Kể các chống chỉ định của kéo dãn.",
      "Vì sao không kéo dãn co rút đang giúp ổn định chức năng ở người bệnh tổn thương tủy cổ?",
    ],
    cases: [
      { text: "Nam 19 tuổi, sinh viên chơi bóng đá, đau mặt sau đùi phải khi chạy nước rút. Kiểm tra nâng chân thẳng thụ động bên phải 60°, bên trái 80°; không đau lưng, không dấu hiệu chèn ép rễ, không có tiền sử rách cơ gần đây.",
        tasks: ["Xác định nhóm cơ cần kéo dãn và giải thích.", "Đề xuất loại kéo dãn, tư thế, cố định và thông số.", "Xây dựng chương trình tự kéo dãn tại nhà kèm hướng dẫn an toàn."] },
    ],
    llo: [
      "Phân tích được cơ chế tác dụng, phân loại, thông số, chỉ định và chống chỉ định của kỹ thuật kéo dãn.",
      "Thực hiện đúng kỹ thuật kéo dãn các nhóm cơ chính, bảo đảm an toàn.",
      "Lựa chọn được kỹ thuật kéo dãn phù hợp với đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành kỹ thuật kéo dãn trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu (suốt cơ, cơ quan gân Golgi, đồ thị creep – stress relaxation).", "Chuẩn bị video kéo dãn các nhóm cơ chính.", "Chuẩn bị 01 tình huống lâm sàng và câu hỏi ôn tập Phần B.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Suy nghĩ về các ứng dụng thực tế (đặc biệt sai lầm khi kéo dãn nảy, kéo khi cơ còn lạnh)."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa; thước đo góc.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: sinh viên cúi người chạm ngón chân trước và sau 30 giây giữ căng, nhận xét sự thay đổi.", "Giới thiệu LLO của bài học."], 5],
      ["2. Cơ chế tác dụng", ["Thuyết giảng tích cực: tính đàn hồi – nhớt (creep, stress relaxation); phản xạ căng, ức chế tự sinh, ức chế đối vận; dung nạp kéo dãn.", "Câu hỏi động não: giải thích hiện tượng vừa trải nghiệm."], 25],
      ["3. Phân loại và thông số", ["Thuyết giảng: kéo dãn tĩnh, động, nảy, thụ động, chủ động, tự kéo dãn, theo nguyên lý PNF (giữ – nghỉ, co – nghỉ).", "Thảo luận nhóm đôi (2 phút): chọn loại kéo dãn cho vận động viên trước thi đấu và cho người bệnh co rút sau bất động."], 20],
      ["4. Chỉ định, chống chỉ định và kỹ thuật", ["Thuyết giảng: chỉ định, chống chỉ định, nguyên tắc an toàn.", "Video & trực quan: kéo dãn cơ ụ ngồi cẳng chân, cơ tam đầu cẳng chân, cơ gập háng; phân tích tư thế cố định."], 20],
      ["5. Dạy học dựa trên tình huống (CBL)", ["Ca lâm sàng ngắn cơ ụ ngồi cẳng chân: nhóm đề xuất kỹ thuật, thông số và chương trình tự tập; giảng viên phản hồi."], 20],
      ["6. Tổng kết và Lượng giá tại lớp", ["Sơ đồ tổng hợp Phần B; lượng giá nhanh 3 câu MCQ.", "Dặn dò ôn tập Phần A, B để chuẩn bị LT1 và TH1."], 10],
    ],
    post: postDefault,
  },

  // ===================== BÀI 8 =====================
  {
    title: "Đại cương về kỹ thuật tạo thuận thần kinh cơ cảm thụ bản thể", short: "Đại cương", lt: 1, part: "C",
    summary: "Bài học mở đầu phần PNF, giới thiệu lịch sử hình thành kỹ thuật tạo thuận thần kinh cơ cảm thụ bản thể do bác sĩ Herman Kabat cùng hai nhà vật lý trị liệu Margaret Knott và Dorothy Voss phát triển từ cuối những năm 1940; định nghĩa PNF qua ba thành tố cảm thụ bản thể, thần kinh cơ và tạo thuận. Sinh viên tìm hiểu triết lý của PNF (tiếp cận tích cực, hướng đến chức năng, huy động khả năng tiềm tàng, tiếp cận toàn diện người bệnh), các nguyên lý thần kinh sinh lý làm nền tảng và tổng quan các nguyên tắc cơ bản của PNF. Bài học tạo khung lý thuyết cho toàn bộ phần PNF.",
    prepIntro: pnf,
    prep: [
      "Các thụ thể cảm thụ bản thể: suốt cơ, cơ quan gân Golgi, thụ thể khớp.",
      "Cung phản xạ, đơn vị vận động và sự kiểm soát vận động của hệ thần kinh.",
      "Lịch sử, định nghĩa và triết lý của PNF.",
      "Các nguyên lý thần kinh sinh lý: lan tỏa, cảm ứng nối tiếp, ức chế đối vận, tổng hợp theo thời gian và không gian, sau phóng điện.",
      "Danh sách các nguyên tắc cơ bản của PNF: kháng trở, lan tỏa và tăng cường, tiếp xúc bằng tay, tư thế và cơ thể học, mệnh lệnh lời nói, thị giác, kéo tách – ép khớp, kéo giãn, thời điểm, mẫu vận động.",
    ],
    reallife: "Sinh viên quan sát các động tác sinh hoạt hằng ngày (chải tóc, đá bóng, xoay người lấy đồ) và nhận xét tính chất chéo – xoắn của vận động chức năng.",
    think: [
      "Người bệnh liệt nửa người: có nên dùng bên lành trong buổi tập không?",
      "Khi kháng trở mạnh ở chân lành, xuất hiện co cơ ở chân liệt.",
    ],
    refs: [R.PNF, R.TK1],
    terms: "Tạo thuận thần kinh cơ cảm thụ bản thể (PNF); Cảm thụ bản thể; Tạo thuận; Lan tỏa (irradiation); Cảm ứng nối tiếp; Ức chế đối vận; Tổng hợp theo thời gian và không gian; Sau phóng điện",
    questions: [
      "Trình bày lịch sử hình thành và định nghĩa của PNF.",
      "Phân tích triết lý cơ bản của PNF.",
      "Giải thích các nguyên lý thần kinh sinh lý được ứng dụng trong PNF.",
      "Kể tên các nguyên tắc cơ bản của PNF.",
    ],
    cases: [
      { text: "Nam 60 tuổi, liệt nửa người trái sau nhồi máu não 6 tuần; gập khuỷu trái yếu, không tự gập hết tầm; bên phải bình thường. Một sinh viên cho rằng “chỉ nên tập bên liệt, không cần quan tâm bên lành”.",
        tasks: ["Dựa vào triết lý PNF, nhận xét ý kiến trên.", "Giải thích bằng nguyên lý lan tỏa và cảm ứng nối tiếp cách dùng nhóm cơ mạnh để tạo thuận cho nhóm cơ yếu."] },
    ],
    llo: [
      "Trình bày được lịch sử, định nghĩa và những nguyên tắc chính của kỹ thuật tạo thuận thần kinh cơ cảm thụ bản thể.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
    ],
    gv: ["Soạn slide trình chiếu nội dung bài học.", "Chuẩn bị video ngắn người bệnh tập PNF và sơ đồ tư duy phần PNF.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Suy nghĩ về tính chất chéo – xoắn của các vận động chức năng hằng ngày."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: chiếu video 1 phút người bệnh tập PNF, hỏi “Điều gì khác với tập vận động thông thường?”", "Giới thiệu LLO của bài học."], 5],
      ["2. Lịch sử và định nghĩa", ["Thuyết giảng tích cực: Kabat, Knott, Voss; ý nghĩa ba thành tố của PNF."], 10],
      ["3. Triết lý và nguyên lý thần kinh sinh lý", ["Thuyết giảng: triết lý PNF; lan tỏa, cảm ứng nối tiếp, ức chế đối vận, tổng hợp, sau phóng điện.", "Thảo luận nhóm đôi (2 phút): tìm ví dụ cho mỗi nguyên lý trong sinh hoạt, tập luyện."], 15],
      ["4. Tổng quan các nguyên tắc cơ bản", ["Thuyết giảng: giới thiệu các nguyên tắc cơ bản và sơ đồ tư duy toàn bộ phần PNF."], 12],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt; lượng giá nhanh 3–5 câu MCQ.", "Dặn dò đọc trước bài Các mẫu chuyển động."], 8],
    ],
    post: postDefault,
  },

  // ===================== BÀI 9 =====================
  {
    title: "Các mẫu chuyển động", lt: 1, part: "C",
    summary: "Bài học trình bày đặc điểm của mẫu chuyển động PNF – chuyển động theo đường chéo và xoắn, phù hợp với cấu trúc của hệ cơ và với các hoạt động chức năng. Sinh viên phân tích ba thành phần của một mẫu (gập/duỗi, dạng/khép, xoay), khái niệm rãnh của mẫu, cách gọi tên mẫu theo khớp gần, hoạt động của các cơ chủ yếu và các loại co cơ trong một mẫu; phân loại mẫu một bên và hai bên (đối xứng, không đối xứng, đối xứng đảo ngược). Bài học là cơ sở để sinh viên thực hiện chính xác các mẫu vận động ở các bài sau.",
    prepIntro: pnf,
    prep: [
      "Giải phẫu – vận động học khớp vai, khớp háng và các cơ chủ yếu ở chi trên, chi dưới.",
      "Các loại co cơ: đẳng trương đồng tâm, ly tâm, giữ ổn định, đẳng trường.",
      "Ba thành phần của một mẫu chuyển động; rãnh của mẫu; cách gọi tên mẫu.",
      "Tên 4 mẫu chi trên, 4 mẫu chi dưới và các cặp mẫu đối vận.",
      "Phân loại mẫu một bên, hai bên đối xứng, không đối xứng, đối xứng đảo ngược.",
    ],
    reallife: "Sinh viên phân tích ba hoạt động chức năng (chải tóc, cài khuy áo, bước lên bậc thang) và xác định mẫu PNF tương ứng.",
    think: [
      "Động tác ném bóng và đá bóng diễn ra theo hướng nào?",
      "Người bệnh khó chải tóc sau gãy đầu trên xương cánh tay.",
    ],
    refs: [R.PNF, R.TK2],
    terms: "Mẫu chuyển động; Đường chéo – xoắn; Rãnh của mẫu (groove); Gập – Dạng – Xoay ngoài; Duỗi – Khép – Xoay trong; Gập – Khép – Xoay ngoài; Duỗi – Dạng – Xoay trong; Co đồng tâm; Co ly tâm; Mẫu hai bên đối xứng; Mẫu hai bên không đối xứng; Mẫu đối xứng đảo ngược",
    questions: [
      "Trình bày ba thành phần của một mẫu chuyển động và cách gọi tên mẫu.",
      "Kể tên 4 mẫu chi trên, 4 mẫu chi dưới và chỉ ra các cặp mẫu đối vận.",
      "Phân tích hoạt động của các cơ chủ yếu trong mẫu chi trên Gập – Dạng – Xoay ngoài.",
      "Phân biệt mẫu hai bên đối xứng, không đối xứng và đối xứng đảo ngược; cho ví dụ chức năng.",
    ],
    cases: [
      { text: "Nữ 40 tuổi, sau phẫu thuật kết hợp xương gãy đầu trên xương cánh tay phải đã liền xương, khó khăn khi chải tóc và với lấy đồ trên giá cao.",
        tasks: ["Phân tích động tác chải tóc và xác định mẫu chi trên tương ứng.", "Mô tả thành phần của mẫu ở vai, khuỷu, cổ tay, ngón và các cơ chủ yếu tham gia."] },
    ],
    llo: [
      "Trình bày đúng và đầy đủ các thành phần của một mẫu chuyển động.",
      "Phân tích được hoạt động của các cơ chủ yếu và các loại co cơ trong một mẫu chuyển động.",
      "Thực hiện đúng các mẫu chuyển động trên cơ thể người học.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các mẫu chuyển động của PNF trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu (hình/hoạt họa đường chéo của các mẫu).", "Chuẩn bị bảng thành phần mẫu và bộ câu hỏi nhận diện mẫu từ hình ảnh."],
    sv: ["Mặc trang phục thuận tiện vận động.", "Suy nghĩ về các vận động chức năng hằng ngày theo đường chéo."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu; bóng nhỏ.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: sinh viên làm động tác ném bóng, đá bóng tại chỗ và nhận xét hướng chuyển động.", "Giới thiệu LLO của bài học."], 5],
      ["2. Thành phần của một mẫu chuyển động", ["Thuyết giảng tích cực: ba thành phần, rãnh của mẫu, gọi tên theo khớp gần; 4 mẫu chi trên, 4 mẫu chi dưới, các cặp đối vận."], 15],
      ["3. Cơ chủ yếu và các loại co cơ", ["Phân tích mẫu chi trên Gập – Dạng – Xoay ngoài.", "Thảo luận nhóm đôi: phân tích mẫu chi dưới Duỗi – Khép – Xoay ngoài."], 15],
      ["4. Phân loại mẫu", ["Thuyết giảng: mẫu một bên, hai bên đối xứng, không đối xứng, đối xứng đảo ngược; ví dụ chức năng."], 8],
      ["5. Tổng kết và Lượng giá tại lớp", ["Lượng giá nhanh: nhận diện mẫu từ hình ảnh (3–5 câu).", "Dặn dò tự tập các mẫu trước gương."], 7],
    ],
    post: postDefault,
  },

  // ===================== BÀI 10 =====================
  {
    title: "Những thao tác cơ bản của kỹ thuật tạo thuận", lt: 2, part: "C",
    summary: "Bài học trình bày các thao tác cơ bản mà kỹ thuật viên sử dụng để tạo thuận đáp ứng vận động: cách đặt tay (kiểu cầm cơ giun, tiếp xúc theo hướng chuyển động), tư thế và cơ thể học của kỹ thuật viên, cách truyền đạt mệnh lệnh bằng lời nói (lệnh chuẩn bị, lệnh hành động, lệnh sửa sai), sử dụng thị giác; ý nghĩa của kéo giãn, kéo tách và ép khớp; thời điểm bình thường (từ xa đến gần) và thời điểm tác động nhằm nhấn mạnh nhóm cơ yếu. Bài học đồng thời nhấn mạnh quy định thực hành nghề nghiệp, đạo đức và giao tiếp với người bệnh khi tiếp xúc cơ thể. Đây là các thao tác bắt buộc cho mọi mẫu và kỹ thuật PNF.",
    prepIntro: pnf,
    prep: [
      "Cách đặt tay kiểu cầm cơ giun và ưu điểm.",
      "Tư thế và cơ thể học của kỹ thuật viên khi thực hiện mẫu.",
      "Ba loại mệnh lệnh lời nói; vai trò của ngữ điệu và thời điểm ra lệnh.",
      "Ý nghĩa và chỉ định của kéo giãn, kéo tách, ép khớp.",
      "Thời điểm bình thường và thời điểm tác động.",
      "Quy định thực hành nghề nghiệp, quy tắc ứng xử và giao tiếp khi tiếp xúc cơ thể người bệnh.",
    ],
    reallife: "Sinh viên quan sát cách nhân viên y tế giải thích, xin phép trước khi chạm vào người bệnh và ghi lại một ví dụ tốt, một ví dụ cần cải thiện.",
    think: [
      "Kỹ thuật viên nắm chặt cả bàn tay quanh cổ tay người bệnh khi thực hiện mẫu.",
      "Mệnh lệnh “cố lên, cố lên” được nói liên tục suốt động tác.",
      "Người bệnh đứng chịu trọng lượng không vững trên chân yếu.",
    ],
    refs: [R.PNF, R.TK2],
    terms: "Tiếp xúc bằng tay; Cầm kiểu cơ giun (lumbrical grip); Mệnh lệnh lời nói; Kéo giãn (stretch); Kéo tách (traction); Ép khớp (approximation); Thời điểm bình thường; Thời điểm tác động (timing for emphasis); Cơ thể học kỹ thuật viên",
    questions: [
      "Mô tả cách đặt tay kiểu cầm cơ giun và giải thích ưu điểm.",
      "Trình bày ba loại mệnh lệnh; vì sao thời điểm ra lệnh quan trọng?",
      "So sánh ý nghĩa và chỉ định của kéo tách và ép khớp.",
      "Phân biệt thời điểm bình thường và thời điểm tác động; cho ví dụ.",
      "Nêu các nguyên tắc đạo đức và giao tiếp khi thực hiện kỹ thuật có tiếp xúc cơ thể người bệnh.",
    ],
    cases: [
      { text: "Trong buổi thực hành, một sinh viên thực hiện mẫu chi trên cho bạn đóng vai người bệnh: nắm chặt cả bàn tay quanh cổ tay bạn, nói liên tục “cố lên” trong suốt động tác, không giải thích trước và không quan sát nét mặt bạn. Bạn đóng vai than đau cổ tay.",
        tasks: ["Xác định các sai sót về đặt tay, mệnh lệnh và giao tiếp.", "Đề xuất cách thực hiện đúng.", "Liên hệ các tiêu chí tương ứng trong bảng kiểm và rubric TH2."] },
    ],
    llo: [
      "Trình bày được ý nghĩa và cách đặt tay để kích thích tạo thuận.",
      "Trình bày được cách truyền đạt mệnh lệnh để người bệnh thực hiện cử động.",
      "Phân tích được ý nghĩa các kỹ thuật kéo giãn, kéo tách, dồn khớp.",
      "Ứng dụng được thời điểm bình thường và thời điểm tác động trên các mẫu vận động.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp (quy định thực hành nghề nghiệp, đạo đức, giao tiếp với người bệnh) trong quá trình ra quyết định và thực hành các thao tác cơ bản của kỹ thuật tạo thuận trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu nội dung bài học.", "Chuẩn bị video so sánh đặt tay và mệnh lệnh đúng/sai.", "Chuẩn bị phiếu quan sát cho hoạt động đóng vai.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Mặc trang phục thuận tiện vận động.", "Suy nghĩ về cách giao tiếp, xin phép người bệnh trước khi tiếp xúc cơ thể."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa; phiếu quan sát.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: “Điều gì khiến bạn thấy an toàn khi được người khác chạm vào để hướng dẫn vận động?”", "Giới thiệu LLO của bài học."], 5],
      ["2. Đặt tay và tư thế kỹ thuật viên", ["Thuyết giảng tích cực: cầm kiểu cơ giun, tiếp xúc theo hướng chuyển động; cơ thể học kỹ thuật viên.", "Làm mẫu đúng/sai trên sinh viên tình nguyện."], 20],
      ["3. Mệnh lệnh lời nói và thị giác", ["Thuyết giảng: lệnh chuẩn bị – hành động – sửa sai; ngữ điệu.", "Đóng vai nhóm đôi: một sinh viên ra lệnh cho mẫu chi trên, sinh viên kia nhận xét theo phiếu."], 15],
      ["4. Kéo giãn, kéo tách, ép khớp", ["Thuyết giảng: cơ sở thần kinh sinh lý và chỉ định từng thủ thuật; thận trọng ở khớp đau, mất vững.", "Video minh họa."], 20],
      ["5. Thời điểm bình thường và thời điểm tác động", ["Thuyết giảng: trình tự xa → gần; kỹ thuật nhấn mạnh nhóm cơ yếu.", "Ví dụ trên mẫu chi dưới."], 20],
      ["6. Đạo đức và giao tiếp nghề nghiệp", ["Thảo luận: xin phép, giải thích, tôn trọng, bảo đảm kín đáo, quan sát phản ứng người bệnh; liên hệ tiêu chí 4 rubric TH2."], 10],
      ["7. Tổng kết và Lượng giá tại lớp", ["Tóm tắt; lượng giá nhanh 3–5 câu MCQ.", "Dặn dò luyện mệnh lệnh cho buổi thực hành."], 10],
    ],
    post: postDefault,
  },

  // ===================== BÀI 11 =====================
  {
    title: "Những kỹ thuật đặc hiệu", lt: 2, part: "C",
    summary: "Bài học trình bày các kỹ thuật tạo thuận đặc hiệu của PNF và mục tiêu điều trị tương ứng: khởi đầu nhịp nhàng, phối hợp co cơ đẳng trương, đảo nghịch đối vận (đảo nghịch động, đảo nghịch ổn định, ổn định nhịp nhàng), kéo giãn lặp lại, co – nghỉ, giữ – nghỉ và lặp lại. Sinh viên phân tích ý nghĩa, chỉ định của từng kỹ thuật; cách ứng dụng trong các mẫu vận động để đạt mục tiêu khởi động vận động, tăng sức mạnh, tăng ổn định, tăng phối hợp, tăng tầm vận động hoặc giảm đau; và cách áp dụng vào các hoạt động chức năng như lăn trở, ngồi dậy, chuyển tư thế. Bài học giúp sinh viên lựa chọn kỹ thuật phù hợp với kết quả lượng giá và đáp ứng của người bệnh.",
    prepIntro: pnf,
    prep: [
      "Mô tả, mục tiêu và chỉ định của từng kỹ thuật đặc hiệu.",
      "Phân nhóm kỹ thuật: kỹ thuật cho cơ chủ vận, kỹ thuật đảo nghịch đối vận, kỹ thuật thư giãn – tăng tầm vận động.",
      "Phân biệt co – nghỉ và giữ – nghỉ; phân biệt đảo nghịch ổn định và ổn định nhịp nhàng.",
      "Mệnh lệnh tương ứng với từng kỹ thuật.",
      "Các khó khăn vận động thường gặp ở người bệnh thần kinh (khó khởi động, mất vững thân, yếu cơ).",
    ],
    reallife: "Sinh viên liên hệ các khó khăn vận động thường gặp ở người bệnh Parkinson, đột quỵ và người đau vai để dự đoán kỹ thuật PNF phù hợp.",
    think: [
      "Người bệnh Parkinson khó khởi động động tác lăn sang bên.",
      "Người bệnh đột quỵ ngồi mất vững khi với tay.",
      "Người bệnh hạn chế dạng vai kèm đau nhiều khi chuyển động.",
    ],
    refs: [R.PNF, R.TK2, R.TKH],
    terms: "Khởi đầu nhịp nhàng (rhythmic initiation); Phối hợp co cơ đẳng trương (combination of isotonics); Đảo nghịch động (dynamic reversals); Đảo nghịch ổn định (stabilizing reversals); Ổn định nhịp nhàng (rhythmic stabilization); Kéo giãn lặp lại (repeated stretch); Co – nghỉ (contract–relax); Giữ – nghỉ (hold–relax); Lặp lại (replication)",
    questions: [
      "Phân nhóm các kỹ thuật đặc hiệu theo mục tiêu điều trị.",
      "So sánh co – nghỉ và giữ – nghỉ về cách thực hiện và chỉ định.",
      "Phân biệt đảo nghịch động, đảo nghịch ổn định và ổn định nhịp nhàng.",
      "Mô tả cách ứng dụng khởi đầu nhịp nhàng trong hoạt động lăn trở.",
      "Dựa vào đâu để lựa chọn kỹ thuật đặc hiệu cho một người bệnh cụ thể?",
    ],
    cases: [
      { text: "Nam 67 tuổi, liệt nửa người phải sau đột quỵ 2 tháng; ngồi được nhưng thân nghiêng và mất vững khi với tay; chuyển từ nằm sang ngồi cần trợ giúp vừa; cơ gập háng phải yếu; nhận thức tốt, hợp tác.",
        tasks: ["Xác định hai vấn đề vận động ưu tiên.", "Lựa chọn kỹ thuật đặc hiệu cho từng vấn đề và giải thích.", "Mô tả cách áp dụng kỹ thuật vào hoạt động ngồi với tay và chuyển nằm – ngồi, kèm mệnh lệnh."] },
      { text: "Nữ 50 tuổi, hạn chế dạng vai phải còn 90°, đau tăng rõ khi cố dạng thêm; không có tổn thương xương khớp cấp tính.",
        tasks: ["Lựa chọn kỹ thuật đặc hiệu để tăng tầm vận động và giải thích.", "Mô tả mệnh lệnh và các lưu ý an toàn."] },
    ],
    llo: [
      "Trình bày được ý nghĩa của những kỹ thuật tạo thuận đặc hiệu.",
      "Ứng dụng được các kỹ thuật đặc hiệu trong các mẫu vận động để đạt được mục tiêu cụ thể.",
      "Lựa chọn được kỹ thuật đặc hiệu phù hợp cho các hoạt động chức năng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các kỹ thuật đặc hiệu của PNF trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: ["Soạn slide trình chiếu và video từng kỹ thuật đặc hiệu.", "Chuẩn bị bảng phân nhóm kỹ thuật theo mục tiêu.", "Chuẩn bị 3 tình huống lâm sàng ngắn cho thảo luận nhóm.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Lập bảng các kỹ thuật đặc hiệu (bản nháp) trước buổi học.", "Suy nghĩ về các khó khăn vận động của người bệnh thần kinh đã gặp."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở: “Cùng một mẫu vận động, làm sao đạt mục tiêu khác nhau: tăng sức mạnh, tăng ổn định hay tăng tầm vận động?”", "Giới thiệu LLO của bài học."], 5],
      ["2. Ý nghĩa và phân nhóm kỹ thuật", ["Thuyết giảng tích cực: phân nhóm theo mục tiêu; nguyên tắc chọn kỹ thuật từ kết quả lượng giá."], 15],
      ["3. Kỹ thuật cho cơ chủ vận", ["Thuyết giảng và làm mẫu: khởi đầu nhịp nhàng, phối hợp co cơ đẳng trương, kéo giãn lặp lại; mệnh lệnh tương ứng."], 20],
      ["4. Đảo nghịch đối vận", ["Thuyết giảng và làm mẫu: đảo nghịch động, đảo nghịch ổn định, ổn định nhịp nhàng.", "Câu hỏi động não: phân biệt 3 kỹ thuật qua video."], 20],
      ["5. Thư giãn – tăng tầm vận động", ["Thuyết giảng: co – nghỉ, giữ – nghỉ, lặp lại; thận trọng khi người bệnh đau."], 15],
      ["6. Dạy học dựa trên tình huống (CBL)", ["Nhóm phân tích 3 tình huống: khó khởi động (Parkinson); mất vững thân (đột quỵ); hạn chế tầm do đau vai. Đại diện trình bày; giảng viên phản hồi."], 15],
      ["7. Tổng kết và Lượng giá tại lớp", ["Bảng tổng hợp kỹ thuật – mục tiêu; lượng giá nhanh 3 câu MCQ.", "Dặn dò chuẩn bị thực hành."], 10],
    ],
    post: postDefault,
  },

  // ===================== BÀI 12 =====================
  {
    title: "Các mẫu PNF của cổ", lt: 2, part: "C",
    summary: "Bài học trình bày tiến trình cơ bản để thực hiện một mẫu vận động PNF và áp dụng cho vùng cổ: mẫu gập kèm nghiêng và xoay về một bên, mẫu duỗi kèm nghiêng và xoay về bên đối diện; tư thế người bệnh, tư thế kỹ thuật viên, vị trí đặt tay, mệnh lệnh và thời điểm. Sinh viên phân tích vai trò của mẫu cổ trong kiểm soát đầu – cổ và trong tạo thuận, lan tỏa sang thân, cùng các lưu ý an toàn đặc thù vùng cổ (tránh kéo tách mạnh, theo dõi chóng mặt, thận trọng với mất vững cột sống cổ và bệnh lý động mạch đốt sống). Bài học giúp sinh viên lựa chọn mẫu và kỹ thuật phù hợp cho các trường hợp đau cổ, hạn chế vận động cổ, kém kiểm soát đầu.",
    prepIntro: pnf,
    prep: [
      "Giải phẫu – vận động học cột sống cổ; các cơ gập, duỗi, nghiêng, xoay cổ.",
      "Tiến trình cơ bản cho một mẫu vận động: tư thế, đặt tay, kéo giãn – kéo tách, mệnh lệnh, chuyển động có kháng trở, thời điểm, vị trí kết thúc.",
      "Các mẫu cổ: gập – nghiêng – xoay về một bên và mẫu đối vận duỗi – nghiêng – xoay về bên đối diện.",
      "Vị trí đặt tay và mệnh lệnh cho các mẫu cổ.",
      "Các dấu hiệu cảnh báo vùng cổ cần dừng tập và báo bác sĩ.",
    ],
    reallife: "Sinh viên quan sát tư thế cúi đầu khi sử dụng điện thoại và liên hệ với tình trạng hạn chế vận động cổ.",
    think: [
      "Người bệnh hạn chế xoay cổ sang phải sau khi ngủ sai tư thế.",
      "Người bệnh chóng mặt khi ngửa cổ trong lúc tập.",
      "Người bệnh đột quỵ kiểm soát đầu kém khi ngồi.",
    ],
    refs: [R.PNF, R.TK2],
    terms: "Tiến trình cơ bản; Mẫu gập cổ kèm nghiêng – xoay; Mẫu duỗi cổ kèm nghiêng – xoay; Kiểm soát đầu; Lan tỏa sang thân; Dấu hiệu cảnh báo (red flags)",
    questions: [
      "Trình bày tiến trình cơ bản cho một mẫu vận động PNF.",
      "Mô tả tư thế người bệnh, tư thế kỹ thuật viên, vị trí tay và mệnh lệnh cho mẫu gập cổ – nghiêng – xoay trái.",
      "Nêu mẫu đối vận của mẫu trên.",
      "Nêu các lưu ý an toàn khi thực hiện mẫu PNF vùng cổ.",
      "Phân tích cách dùng mẫu cổ để tạo thuận cho thân.",
    ],
    cases: [
      { text: "Nam 32 tuổi, đau và hạn chế xoay cổ sang phải 2 tuần sau khi ngủ sai tư thế; không chấn thương, không tê tay, không chóng mặt; co cứng cơ ức đòn chũm và cơ thang bên trái; đau khi chuyển động cuối tầm.",
        tasks: ["Lựa chọn mẫu cổ phù hợp để tăng tầm xoay phải và giải thích.", "Lựa chọn kỹ thuật đặc hiệu phù hợp (lưu ý có đau) và mô tả mệnh lệnh.", "Nêu nội dung theo dõi an toàn trong quá trình thực hiện."] },
    ],
    llo: PNF_LLO("cổ"),
    gv: ["Soạn slide trình chiếu và video các mẫu cổ.", "Chuẩn bị bàn tập/ghế để làm mẫu trên giảng đường.", "Chuẩn bị 01 tình huống lâm sàng ngắn.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Mặc trang phục thuận tiện vận động.", "Suy nghĩ về các ứng dụng thực tế (đặc biệt nguy cơ khi kéo tách mạnh vùng cổ)."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa; bàn tập hoặc ghế.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: sinh viên tự xoay – gập cổ, nhận xét sự phối hợp xoay và nghiêng.", "Giới thiệu LLO của bài học."], 5],
      ["2. Tiến trình cơ bản cho một mẫu vận động", ["Câu hỏi gợi mở: ôn các thao tác cơ bản; giảng viên hệ thống hóa thành tiến trình các bước áp dụng cho vùng cổ."], 15],
      ["3. Kỹ thuật thao tác các mẫu cổ", ["Làm mẫu trên sinh viên tình nguyện: mẫu gập – nghiêng – xoay và mẫu đối vận; tư thế nằm ngửa và ngồi.", "Sinh viên quan sát theo phiếu (tư thế – vị trí tay – mệnh lệnh – thời điểm).", "Nhấn mạnh an toàn: không kéo tách mạnh, theo dõi chóng mặt."], 35],
      ["4. Áp dụng cho trường hợp cụ thể (CBL)", ["Nguyên tắc chọn mẫu và kỹ thuật theo mục tiêu.", "Nhóm phân tích ca hạn chế xoay cổ sau ngủ sai tư thế; đề xuất mẫu, kỹ thuật, mệnh lệnh; giảng viên phản hồi."], 30],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt; lượng giá nhanh 3 câu MCQ.", "Dặn dò luyện mệnh lệnh mẫu cổ cho buổi thực hành."], 15],
    ],
    post: postDefault,
  },

  // ===================== BÀI 13 =====================
  {
    title: "Các mẫu PNF của thân", lt: 2, part: "C",
    summary: "Bài học áp dụng tiến trình cơ bản của PNF cho vùng thân: mẫu chặt (gập thân kèm xoay) và mẫu nâng (duỗi thân kèm xoay) được dẫn dắt bởi mẫu hai chi trên không đối xứng; mẫu hai chi dưới để tạo thuận thân dưới; phối hợp mẫu cổ với mẫu thân. Sinh viên tìm hiểu tư thế người bệnh, vị trí đặt tay, mệnh lệnh, thời điểm và các lưu ý an toàn cho cột sống. Trọng tâm là ứng dụng mẫu thân trong các hoạt động chức năng như lăn trở, chuyển từ nằm sang ngồi, kiểm soát thân khi ngồi và với tay ở người bệnh đột quỵ, đau thắt lưng.",
    prepIntro: pnf,
    prep: [
      "Vận động học thân: cơ thẳng bụng, cơ chéo bụng, cơ duỗi lưng, cơ vuông thắt lưng.",
      "Vai trò của kiểm soát thân trong ngồi, đứng và chuyển tư thế.",
      "Mẫu chặt, mẫu nâng; mẫu hai chi dưới cho thân dưới.",
      "Vị trí đặt tay và mệnh lệnh cho các mẫu thân.",
      "Lưu ý an toàn cột sống khi thực hiện mẫu thân.",
    ],
    reallife: "Sinh viên quan sát người cao tuổi chuyển từ nằm sang ngồi và phân tích vai trò của gập thân kèm xoay trong động tác này.",
    think: [
      "Người bệnh liệt nửa người trái khó lăn sang bên trái.",
      "Người bệnh ngồi không tựa thì nghiêng về bên liệt.",
    ],
    refs: [R.PNF, R.TK2, R.TKH],
    terms: "Mẫu chặt (chopping); Mẫu nâng (lifting); Mẫu hai chi trên không đối xứng; Mẫu hai chi dưới; Kiểm soát thân; Lăn trở; Chuyển nằm – ngồi",
    questions: [
      "Mô tả mẫu chặt và mẫu nâng: thành phần, tư thế, vị trí tay, mệnh lệnh.",
      "Phân tích cách dùng mẫu hai chi dưới để tạo thuận cơ thân dưới.",
      "Trình bày ứng dụng mẫu thân trong hoạt động lăn trở và chuyển nằm – ngồi.",
      "Kỹ thuật đặc hiệu nào thường phối hợp với mẫu thân để tăng ổn định khi ngồi?",
    ],
    cases: [
      { text: "Nữ 70 tuổi, liệt nửa người trái sau đột quỵ 5 tuần; lăn sang phải được nhưng lăn sang trái khó; chuyển từ nằm sang ngồi cần trợ giúp nhiều; ngồi có tựa ổn định, không tựa thì nghiêng về bên trái. Không đau lưng, không loãng xương nặng.",
        tasks: ["Xác định vấn đề kiểm soát thân ưu tiên.", "Lựa chọn mẫu thân và kỹ thuật đặc hiệu để tạo thuận lăn trở, chuyển nằm – ngồi; mô tả mệnh lệnh.", "Đề xuất cách tăng ổn định thân khi ngồi."] },
    ],
    llo: PNF_LLO("thân"),
    gv: ["Soạn slide trình chiếu và video mẫu chặt, nâng, mẫu hai chi dưới.", "Chuẩn bị bàn tập để làm mẫu.", "Chuẩn bị 01 tình huống lâm sàng ngắn.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Mặc trang phục thuận tiện vận động.", "Suy nghĩ về vai trò kiểm soát thân trong sinh hoạt hằng ngày."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa; bàn tập.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: sinh viên mô phỏng động tác ngồi dậy và với tay lấy đồ phía sau, nhận diện gập/duỗi thân kèm xoay.", "Giới thiệu LLO của bài học."], 5],
      ["2. Tiến trình cơ bản áp dụng cho thân", ["Câu hỏi gợi mở; giảng viên hệ thống hóa tiến trình các bước áp dụng cho các mẫu thân."], 15],
      ["3. Kỹ thuật thao tác các mẫu thân", ["Làm mẫu trên sinh viên tình nguyện: mẫu chặt, mẫu nâng ở tư thế ngồi và nằm; mẫu hai chi dưới; phối hợp cổ – thân.", "Sinh viên quan sát theo phiếu; nhấn mạnh cơ thể học kỹ thuật viên và an toàn cột sống."], 35],
      ["4. Áp dụng cho trường hợp cụ thể (CBL)", ["Nhóm phân tích ca liệt nửa người khó lăn trở và ngồi mất vững; đề xuất mẫu, kỹ thuật, mệnh lệnh; giảng viên phản hồi."], 30],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt; lượng giá nhanh 3 câu MCQ.", "Dặn dò chuẩn bị thực hành."], 15],
    ],
    post: postDefault,
  },

  // ===================== BÀI 14 =====================
  {
    title: "Các mẫu PNF của chi trên", lt: 2, part: "C",
    summary: "Bài học áp dụng tiến trình cơ bản cho chi trên: các mẫu xương bả vai (nâng ra trước – hạ ra sau, nâng ra sau – hạ ra trước) và bốn mẫu chi trên theo hai đường chéo: Gập – Dạng – Xoay ngoài, Duỗi – Khép – Xoay trong, Gập – Khép – Xoay ngoài, Duỗi – Dạng – Xoay trong, kèm các biến thể khuỷu gập, khuỷu duỗi, khuỷu thẳng. Với mỗi mẫu, sinh viên tìm hiểu tư thế, vị trí tay, kéo giãn ở đầu tầm, mệnh lệnh, thời điểm và vị trí kết thúc. Bài học giúp sinh viên lựa chọn mẫu và kỹ thuật đặc hiệu cho người bệnh liệt nửa người, hạn chế vận động vai, yếu cơ chi trên, gắn với hoạt động chức năng.",
    prepIntro: pnf,
    prep: [
      "Giải phẫu – vận động học đai vai, khớp vai, khuỷu, cổ tay, bàn tay.",
      "Các mẫu xương bả vai và vai trò đối với chức năng chi trên.",
      "Thành phần của 4 mẫu chi trên ở vai, khuỷu, cổ tay, ngón; các biến thể khuỷu.",
      "Vị trí đặt tay (tay xa, tay gần) và mệnh lệnh cho từng mẫu.",
      "Lưu ý an toàn khớp vai ở người bệnh liệt nửa người.",
    ],
    reallife: "Sinh viên phân tích ba hoạt động sinh hoạt (chải tóc, đưa tay ra sau lưng, với lấy đồ trên cao) theo các mẫu chi trên.",
    think: [
      "Người bệnh liệt nửa người muốn tự chải tóc và tự ăn bằng tay bên liệt.",
      "Người bệnh liệt nửa người có bán trật khớp vai.",
    ],
    refs: [R.PNF, R.TK2, R.TKH],
    terms: "Mẫu xương bả vai; Gập – Dạng – Xoay ngoài; Duỗi – Khép – Xoay trong; Gập – Khép – Xoay ngoài; Duỗi – Dạng – Xoay trong; Khuỷu gập; Khuỷu duỗi; Tay xa; Tay gần; Đầu tầm; Vị trí kết thúc",
    questions: [
      "Mô tả thành phần của 4 mẫu chi trên ở vai, khuỷu, cổ tay, ngón.",
      "Trình bày tư thế, vị trí tay và mệnh lệnh cho mẫu Gập – Dạng – Xoay ngoài khuỷu thẳng.",
      "Ở đầu tầm của mẫu Gập – Khép – Xoay ngoài, chi trên ở tư thế nào?",
      "Nêu vai trò của các mẫu xương bả vai đối với chức năng chi trên.",
      "Phân tích cách chọn mẫu và kỹ thuật đặc hiệu cho người bệnh liệt nửa người yếu cơ gập vai.",
    ],
    cases: [
      { text: "Nữ 58 tuổi, liệt nửa người phải sau nhồi máu não 8 tuần; vai phải gập chủ động 60°, không đau vai, không bán trật khớp vai; cầm nắm thô được; mong muốn tự chải tóc và tự ăn bằng tay phải.",
        tasks: ["Phân tích các hoạt động chức năng mục tiêu theo mẫu chi trên.", "Lựa chọn mẫu, biến thể khuỷu và kỹ thuật đặc hiệu; giải thích.", "Mô tả vị trí tay, mệnh lệnh và lưu ý an toàn khớp vai."] },
    ],
    llo: PNF_LLO("chi trên"),
    gv: ["Soạn slide trình chiếu và video 4 mẫu chi trên, mẫu xương bả vai.", "Chuẩn bị bàn tập, mô hình khớp vai.", "Chuẩn bị 01 tình huống lâm sàng ngắn.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Mặc trang phục thuận tiện vận động.", "Tự thực hiện chủ động 4 mẫu chi trên trước gương."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa; bàn tập, mô hình khớp vai.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: sinh viên thực hiện động tác chải tóc, với lấy đồ, đưa tay ra sau và nhận diện đường chéo.", "Giới thiệu LLO của bài học."], 5],
      ["2. Tiến trình cơ bản áp dụng cho chi trên", ["Câu hỏi gợi mở; hệ thống hóa tiến trình các bước; vai trò chuẩn bị xương bả vai."], 15],
      ["3. Kỹ thuật thao tác các mẫu chi trên", ["Làm mẫu trên sinh viên tình nguyện: mẫu xương bả vai; hai cặp mẫu chéo chi trên; biến thể khuỷu gập, khuỷu duỗi.", "Sinh viên quan sát theo phiếu; nhấn mạnh an toàn khớp vai."], 35],
      ["4. Áp dụng cho trường hợp cụ thể (CBL)", ["Nhóm phân tích ca liệt nửa người muốn tự chải tóc, tự ăn; đề xuất mẫu, kỹ thuật, mệnh lệnh; giảng viên phản hồi."], 30],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt; lượng giá nhanh: nhận diện mẫu từ hình ảnh (3 câu).", "Dặn dò chuẩn bị thực hành."], 15],
    ],
    post: postDefault,
  },

  // ===================== BÀI 15 =====================
  {
    title: "Các mẫu PNF của chi dưới", lt: 2, part: "C",
    summary: "Bài học áp dụng tiến trình cơ bản cho chi dưới: các mẫu khung chậu (nâng ra trước – hạ ra sau, nâng ra sau – hạ ra trước) và bốn mẫu chi dưới: Gập – Dạng – Xoay trong, Duỗi – Khép – Xoay ngoài, Gập – Khép – Xoay ngoài, Duỗi – Dạng – Xoay trong, kèm các biến thể gối gập, gối duỗi, gối thẳng. Sinh viên tìm hiểu tư thế, vị trí tay, kéo giãn ở đầu tầm, mệnh lệnh, thời điểm và vị trí kết thúc; vận dụng mẫu khung chậu và mẫu chi dưới trong lăn trở, bắc cầu, đứng chịu trọng lượng và các pha của dáng đi. Bài học khép lại phần PNF, giúp sinh viên lựa chọn mẫu và kỹ thuật phù hợp cho người bệnh liệt nửa người, sau chấn thương – phẫu thuật chi dưới.",
    prepIntro: pnf,
    prep: [
      "Giải phẫu – vận động học khung chậu, háng, gối, cổ chân.",
      "Các pha của chu kỳ dáng đi (pha đứng, pha đu đưa).",
      "Các mẫu khung chậu và vai trò trong lăn trở, dáng đi.",
      "Thành phần của 4 mẫu chi dưới ở háng, gối, cổ chân, ngón; các biến thể gối.",
      "Vị trí đặt tay và mệnh lệnh cho từng mẫu.",
    ],
    reallife: "Sinh viên quan sát dáng đi của người cao tuổi và người bệnh liệt nửa người, xác định pha dáng đi bị ảnh hưởng.",
    think: [
      "Người bệnh liệt nửa người kéo lê bàn chân ở pha đu đưa.",
      "Người bệnh đứng chịu trọng lượng không vững trên chân liệt.",
    ],
    refs: [R.PNF, R.TK2, R.TKH],
    terms: "Mẫu khung chậu; Gập – Dạng – Xoay trong; Duỗi – Khép – Xoay ngoài; Gập – Khép – Xoay ngoài; Duỗi – Dạng – Xoay trong; Gối gập; Gối duỗi; Pha đứng; Pha đu đưa; Bắc cầu",
    questions: [
      "Mô tả thành phần của 4 mẫu chi dưới ở háng, gối, cổ chân, ngón.",
      "Ở mẫu Gập – Dạng – Xoay trong, thành phần cổ chân là gì?",
      "Trình bày tư thế, vị trí tay và mệnh lệnh cho mẫu Gập – Khép – Xoay ngoài gối gập.",
      "Nêu vai trò của các mẫu khung chậu trong lăn trở và dáng đi.",
      "Phân tích cách dùng mẫu chi dưới và kỹ thuật đặc hiệu để tạo thuận pha đu đưa ở người bệnh liệt nửa người.",
    ],
    cases: [
      { text: "Nam 63 tuổi, liệt nửa người trái sau xuất huyết não 3 tháng; đi được với gậy một chân nhưng kéo lê bàn chân trái ở pha đu đưa, khung chậu trái nâng lên – xoay ra sau khi bước; đứng chịu trọng lượng bên trái chưa vững; không đau, không co rút cổ chân.",
        tasks: ["Phân tích các vấn đề dáng đi theo pha đứng và pha đu đưa.", "Lựa chọn mẫu khung chậu, mẫu chi dưới, biến thể gối và kỹ thuật đặc hiệu cho từng vấn đề; giải thích.", "Mô tả vị trí tay, mệnh lệnh và cách chuyển kết quả tập sang hoạt động đi."] },
    ],
    llo: PNF_LLO("chi dưới"),
    gv: ["Soạn slide trình chiếu và video 4 mẫu chi dưới, mẫu khung chậu.", "Chuẩn bị video dáng đi liệt nửa người (ẩn danh, có sự đồng ý).", "Chuẩn bị 01 tình huống lâm sàng và câu hỏi ôn tập phần PNF.", "Thiết lập bộ câu hỏi lượng giá nhanh."],
    sv: ["Mặc trang phục thuận tiện vận động.", "Tự thực hiện chủ động 4 mẫu chi dưới trước gương."],
    materials: "Máy chiếu, bảng, bút viết, laptop, slide trình chiếu, loa; bàn tập.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Kích thích tư duy: chiếu video dáng đi liệt nửa người, sinh viên nhận xét bất thường ở khung chậu, háng, gối, cổ chân.", "Giới thiệu LLO của bài học."], 5],
      ["2. Tiến trình cơ bản áp dụng cho chi dưới", ["Câu hỏi gợi mở; hệ thống hóa tiến trình các bước; vai trò mẫu khung chậu."], 15],
      ["3. Kỹ thuật thao tác các mẫu chi dưới", ["Làm mẫu trên sinh viên tình nguyện: mẫu khung chậu; hai cặp mẫu chéo chi dưới; biến thể gối gập, gối duỗi.", "Sinh viên quan sát theo phiếu; nhấn mạnh cơ thể học kỹ thuật viên khi nâng đỡ chi dưới."], 35],
      ["4. Áp dụng cho trường hợp cụ thể (CBL)", ["Nhóm phân tích ca liệt nửa người kéo lê bàn chân; đề xuất mẫu, kỹ thuật, mệnh lệnh; giảng viên phản hồi."], 30],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt phần PNF; lượng giá nhanh 3–5 câu MCQ.", "Dặn dò ôn tập để chuẩn bị LT2, TH2 và thi kết thúc học phần."], 15],
    ],
    post: postDefault,
  },
];
