// Phụ lục 3, 4 – bản v3: nội dung Phần A (điện trị liệu) và Phần C (PNF) chỉ lấy từ ĐCCT 2024:
//  - BLC024467 Bệnh lý và VLTL hệ cơ – xương (Phần 1: Các phương thức điều trị vật lý): Mục 4, Mục 5, Phụ lục 1, Phụ lục 2
//  - BLN024494 Bệnh lý và VLTL hệ thần kinh – cơ nâng cao (Bài 1–8: PNF): Mục 4, Mục 5, Phụ lục 1, Phụ lục 2
// LLO (Phụ lục 4) giữ đúng Mục 5 của ĐCCT 2026. Phần B giữ nguyên bản v2.
const v2 = require("./v2_data.js");

const R = {
  CX: "Lê Quang Khanh, Cao Bích Thủy (2016), Bài giảng Bệnh lý và vật lý trị liệu hệ cơ xương I. Trường Đại học Kỹ thuật Y - Dược Đà Nẵng. Lưu hành nội bộ.",
  HO: "Bản handout file trình chiếu.",
  LKD: "Lê Khánh Điền, Nguyễn Thị Hương (2008), Kỹ thuật tạo thuận cảm thụ bản thể thần kinh cơ. Nhà xuất bản Y học, Hà Nội.",
  ADL: "Susan S. Adler, Dominiek Beckers, Math Buck (2014), PNF in Practice. Springer-Verlag Berlin Heidelberg.",
  NTD: "Nguyễn Tấn Dũng, Lê Quang Khanh (2015), Bệnh lý và vật lý trị liệu thần kinh cơ nâng cao. Trường Đại học Kỹ thuật Y - Dược Đà Nẵng. Lưu hành nội bộ.",
};
const elec = "Sinh viên đọc, nghiên cứu Bài giảng Bệnh lý và vật lý trị liệu hệ cơ xương I trước ở nhà, mục tiêu bài học và quy trình kỹ thuật. Trước khi học, sinh viên cần nắm:";
const pnf = "Sinh viên đọc, nghiên cứu các tài liệu chuyên môn và bản handout file trình chiếu trước ở nhà. Trước khi học, sinh viên cần nắm:";
const elecMind = "Sinh viên vẽ sơ đồ tư duy liên hệ chuyên môn và các lĩnh vực kiến thức/môn học đã, đang và sẽ học; chỉ ra mối quan hệ của các phương thức điều trị vật lý với các môn học khác.";
const post = ["Làm bài quiz ngắn (5 câu) trên hệ thống E-learning trước buổi học kế tiếp.", "Gửi câu hỏi thắc mắc vào diễn đàn lớp học trên E-learning."];
// Các bước của bảng kiểm kỹ thuật điều trị vật lý (Phụ lục 2 – BLC024467)
const machineSteps = "chào hỏi, giao tiếp, kiểm tra thông tin người bệnh; hướng dẫn, giải thích kỹ thuật; thông báo cảm giác điều trị và cách phản ứng khi có dấu hiệu bất thường; đặt tư thế điều trị; tư thế kỹ thuật viên; bộc lộ vùng điều trị; chỉnh thông số máy; dùng máy đúng cách; xử trí khi người bệnh phản hồi về cảm giác điều trị; kết thúc điều trị";
const PNF_LLO = (v) => [
  "Trình bày được các tiến trình cơ bản cho một mẫu vận động.",
  `Trình bày được kỹ thuật thao tác cho các mẫu ở ${v}.`,
  `Thực hiện đúng kỹ thuật thao tác các mẫu vận động ở ${v}.`,
  `Lựa chọn được mẫu và kỹ thuật PNF phù hợp cho trường hợp điều trị cụ thể ở ${v}.`,
  "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
  `Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các mẫu PNF của ${v} trên mô hình hoặc tình huống lâm sàng giả định.`,
];
const elecGV = ["Soạn slide trình chiếu (powerpoint) có hình ảnh, phim minh họa.", "Chuẩn bị câu hỏi mở và trò chơi động não (trả lời nhanh, câu trả lời tiếp sức, sơ đồ tư duy).", "Chuẩn bị bài tập nhóm/nghiên cứu tình huống."];
const pnfGV = ["Soạn slide trình chiếu (powerpoint) và bản handout.", "Chuẩn bị hình ảnh, video minh họa thao tác.", "Chuẩn bị câu hỏi mở, trò chơi động não và bài tập nhóm."];

// Mẫu bảng hoạt động cho các bài mẫu PNF theo vùng (100 phút)
const regionActs = (o) => [
  ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở: " + o.open, "Giới thiệu LLO của bài học."], 5],
  ["2. Giới thiệu và những tiến trình cơ bản", ["Thuyết giảng tích cực (powerpoint, hình ảnh): giới thiệu và những tiến trình cơ bản cho một mẫu vận động.", o.purpose], 20],
  ["3. Các mẫu " + o.region, ["Thuyết giảng kết hợp video: " + o.patterns + ".", "Giảng viên minh họa thao tác trên sinh viên đóng vai; sinh viên quan sát."], 35],
  ["4. Áp dụng cho bệnh nhân cụ thể", ["Câu hỏi mở, nghiên cứu tình huống: áp dụng các thao tác cơ bản và kỹ thuật đặc hiệu khi thực hiện " + o.n + " ở " + o.region + ".", "Học nhóm: xác định các điểm cần ghi nhớ khi thao tác các mẫu " + o.region + "; đại diện nhóm trình bày."], 25],
  ["5. Tổng kết và Lượng giá tại lớp", ["Trò chơi trả lời nhanh: tóm tắt các mẫu " + o.region + ".", "Dặn dò xem video mẫu PNF " + o.region + ", đóng vai tự thực hiện kỹ thuật với bạn học trước buổi thực hành."], 15],
];

const A = [
  // ===================== BÀI 1 =====================
  {
    title: "Năng lượng bức xạ, các định luật và điều trị bằng tia", lt: 1, part: "A",
    summary: "Bài học trình bày điện từ phổ, sự phát sinh và đặc tính của sóng điện từ, quá trình phản chiếu, khúc xạ và hấp thu; tia hồng ngoại trong vật lý trị liệu với các nguồn phát xạ, tác dụng sinh lý, tác dụng điều trị và ứng dụng lâm sàng; các chống chỉ định, những tai biến và cách điều trị bằng hồng ngoại. Bài học trang bị cho sinh viên kiến thức về tác dụng sinh lý, tác dụng điều trị, ứng dụng lâm sàng, tai biến và các biện pháp an toàn, chỉ định và chống chỉ định, làm cơ sở để thực hiện đúng kỹ thuật điều trị bằng tia hồng ngoại trên bệnh nhân giả định theo quy trình.",
    prepIntro: elec,
    prep: [
      "Các khái niệm, thuật ngữ về năng lượng bức xạ; điện từ phổ.",
      "Sự phát sinh và đặc tính của sóng điện từ; quá trình phản chiếu, khúc xạ và hấp thu.",
      "Các nguồn phát xạ tia hồng ngoại.",
      "Tác dụng sinh lý, tác dụng điều trị và ứng dụng lâm sàng của tia hồng ngoại.",
      "Chống chỉ định của tia hồng ngoại trong điều trị; những tai biến khi điều trị bằng tia hồng ngoại.",
      "Quy trình kỹ thuật điều trị bằng tia hồng ngoại.",
    ],
    reallife: elecMind,
    think: ["Lên danh sách các bệnh được áp dụng điều trị bằng tia hồng ngoại.", "Những tai biến nào có thể xảy ra khi điều trị bằng tia hồng ngoại và cách xử trí?"],
    refs: [R.CX],
    terms: "Năng lượng bức xạ; Điện từ phổ; Sóng điện từ; Phản chiếu; Khúc xạ; Hấp thu; Tia hồng ngoại; Nguồn phát xạ; Tác dụng sinh lý; Tác dụng điều trị; Tai biến",
    questions: [
      "Trình bày điện từ phổ, sự phát sinh và đặc tính của sóng điện từ.",
      "Mô tả quá trình phản chiếu, khúc xạ và hấp thu của năng lượng bức xạ.",
      "Trình bày các nguồn phát xạ tia hồng ngoại.",
      "Trình bày tác dụng sinh lý, tác dụng điều trị và ứng dụng lâm sàng của tia hồng ngoại.",
      "Kể các chống chỉ định và những tai biến khi điều trị bằng tia hồng ngoại.",
    ],
    cases: [
      { text: "Một bệnh nhân giả định được chỉ định điều trị bằng tia hồng ngoại tại phòng thực hành.",
        tasks: ["Liệt kê các chống chỉ định cần kiểm tra trước khi điều trị.", "Trình bày các bước thực hiện kỹ thuật theo bảng kiểm: " + machineSteps + ".", "Nêu những tai biến có thể xảy ra và cách xử trí."] },
    ],
    llo: [
      "Mô tả được sự phát sinh, đặc tính sóng của điện từ và các quá trình phản chiếu, khúc xạ, hấp thu.",
      "Phân tích được nguồn phát xạ, tác dụng sinh lý, tác dụng điều trị, ứng dụng lâm sàng, chống chỉ định và tai biến của tia hồng ngoại.",
      "Thực hiện đúng kỹ thuật điều trị bằng tia hồng ngoại trên người bệnh giả định theo quy trình.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành kỹ thuật điều trị bằng tia hồng ngoại trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: elecGV,
    sv: ["Lên danh sách các bệnh được áp dụng điều trị bằng tia hồng ngoại."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở về các ứng dụng của tia hồng ngoại.", "Giới thiệu LLO của bài học."], 5],
      ["2. Điện từ phổ và sóng điện từ", ["Thuyết giảng tích cực (powerpoint, hình ảnh): điện từ phổ; sự phát sinh và đặc tính của sóng điện từ; phản chiếu, khúc xạ, hấp thu."], 12],
      ["3. Tia hồng ngoại trong vật lý trị liệu", ["Thuyết giảng: nguồn phát xạ, tác dụng sinh lý, tác dụng điều trị và ứng dụng lâm sàng.", "Trò chơi động não: sinh viên trả lời nhanh danh sách các bệnh được áp dụng."], 15],
      ["4. Chống chỉ định, tai biến và kỹ thuật điều trị", ["Thuyết giảng kết hợp phim minh họa: chống chỉ định, những tai biến và cách điều trị bằng hồng ngoại; quy trình kỹ thuật."], 12],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt bằng sơ đồ tư duy; câu hỏi nhanh.", "Dặn dò xem lại quy trình trước buổi thực hành."], 6],
    ],
    post,
  },
  // ===================== BÀI 2 =====================
  {
    title: "Điều trị bằng sóng", lt: 5, part: "A",
    summary: "Bài học trình bày bốn phương thức điều trị bằng sóng: dòng cao tần – thâu nhiệt sóng ngắn (đại cương, tác dụng, phương thức sử dụng); laser trong vật lý trị liệu (đại cương, các loại laser dùng trong y học và trong vật lý trị liệu, hiệu quả điều trị của laser trung gian, nguyên tắc tổng quát khi điều trị, chống chỉ định); sóng xung kích (đại cương, các loại sóng xung kích, thiết bị và kỹ thuật điều trị, ứng dụng, an toàn và phòng ngừa); siêu âm điều trị (năng lượng siêu âm, cách tạo siêu âm, tác dụng sinh lý, tác dụng điều trị và ứng dụng lâm sàng, tai biến, chống chỉ định, kỹ thuật trị liệu). Bài học giúp sinh viên chuẩn bị máy và bệnh nhân, thực hiện đúng kỹ thuật điều trị bằng sóng và bảo đảm an toàn cho bệnh nhân và máy trong quá trình điều trị.",
    prepIntro: elec,
    prep: [
      "Các khái niệm về các phương pháp điều trị bằng sóng.",
      "Dòng cao tần – thâu nhiệt sóng ngắn: đại cương, tác dụng, phương thức sử dụng.",
      "Laser: đại cương; các loại laser dùng trong y học và trong vật lý trị liệu; hiệu quả điều trị của laser trung gian; nguyên tắc tổng quát khi điều trị; chống chỉ định.",
      "Sóng xung kích: đại cương; các loại sóng xung kích dùng trong vật lý trị liệu; thiết bị và kỹ thuật điều trị; ứng dụng; an toàn và phòng ngừa.",
      "Siêu âm điều trị: năng lượng siêu âm; cách tạo siêu âm; tác dụng sinh lý; tác dụng điều trị và ứng dụng lâm sàng; tai biến; chống chỉ định; kỹ thuật trị liệu.",
      "Cách chuẩn bị máy và bệnh nhân; các biện pháp bảo đảm an toàn cho bệnh nhân và máy.",
    ],
    reallife: elecMind,
    think: ["Lên danh sách các bệnh được áp dụng điều trị bằng sóng ngắn, laser, sóng xung kích, siêu âm.", "Các biện pháp đề phòng tai biến cho bệnh nhân và máy khi điều trị bằng sóng là gì?"],
    refs: [R.CX],
    terms: "Dòng cao tần; Thâu nhiệt sóng ngắn; Laser; Laser trung gian; Sóng xung kích; Năng lượng siêu âm; Siêu âm điều trị; Tác dụng sinh lý; Tác dụng điều trị; Chống chỉ định; Tai biến; An toàn và phòng ngừa",
    questions: [
      "Trình bày đại cương, tác dụng và phương thức sử dụng thâu nhiệt sóng ngắn.",
      "Kể các loại laser dùng trong y học và trong vật lý trị liệu; trình bày nguyên tắc tổng quát khi điều trị và chống chỉ định của laser.",
      "Trình bày các loại sóng xung kích, thiết bị và kỹ thuật điều trị, các biện pháp an toàn và phòng ngừa.",
      "Trình bày cách tạo siêu âm, tác dụng sinh lý, tác dụng điều trị và kỹ thuật trị liệu bằng siêu âm.",
      "Kể các chống chỉ định, tai biến và biện pháp đề phòng khi điều trị bằng sóng.",
    ],
    cases: [
      { text: "Một bệnh nhân giả định được chỉ định điều trị bằng siêu âm tại phòng thực hành.",
        tasks: ["Trình bày cách chuẩn bị máy và bệnh nhân.", "Trình bày các bước thực hiện theo bảng kiểm: " + machineSteps + ".", "Nêu các tai biến có thể xảy ra và cách xử trí."] },
      { text: "Một bệnh nhân giả định được chỉ định điều trị bằng thâu nhiệt sóng ngắn.",
        tasks: ["Liệt kê các chống chỉ định cần kiểm tra.", "Trình bày các biện pháp bảo đảm an toàn cho bệnh nhân và máy trong quá trình điều trị."] },
    ],
    llo: [
      "Phân tích được đại cương, ứng dụng điều trị, chỉ định, chống chỉ định, tai biến và các biện pháp đề phòng của sóng ngắn, laser, sóng xung kích, siêu âm.",
      "Thực hiện đúng kỹ thuật điều trị bằng sóng, bao gồm chuẩn bị máy và người bệnh, bảo đảm an toàn cho người bệnh và máy.",
      "Lựa chọn được kỹ thuật điều trị bằng sóng phù hợp với chỉ định và đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các kỹ thuật điều trị bằng sóng trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: elecGV,
    sv: ["Lên danh sách các bệnh được áp dụng các phương thức điều trị bằng sóng."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: [
      { section: "Buổi 1 (03 tiết – 150 phút)" },
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở: các khái niệm về các phương pháp điều trị bằng sóng.", "Giới thiệu LLO của bài học."], 10],
      ["2. Dòng cao tần – Thâu nhiệt sóng ngắn", ["Thuyết giảng tích cực (powerpoint, hình ảnh): đại cương; tác dụng; phương thức sử dụng thâu nhiệt sóng ngắn.", "Chống chỉ định, tai biến, biện pháp đề phòng; chuẩn bị máy và bệnh nhân."], 60],
      ["3. Siêu âm điều trị", ["Thuyết giảng kết hợp phim: năng lượng siêu âm; cách tạo siêu âm; tác dụng sinh lý; tác dụng điều trị và ứng dụng lâm sàng.", "Những tai biến và cách điều trị; chống chỉ định; kỹ thuật trị liệu."], 60],
      ["4. Tổng kết buổi 1", ["Trò chơi trả lời nhanh về sóng ngắn và siêu âm.", "Dặn dò đọc trước phần laser, sóng xung kích."], 20],
      { section: "Buổi 2 (02 tiết – 100 phút)" },
      ["1. Mở đầu", ["Câu hỏi mở ôn lại buổi 1; giới thiệu nội dung buổi 2."], 5],
      ["2. Laser trong vật lý trị liệu", ["Thuyết giảng: đại cương; các loại laser dùng trong y học và trong vật lý trị liệu; hiệu quả điều trị của laser trung gian; nguyên tắc tổng quát khi điều trị; chống chỉ định."], 35],
      ["3. Sóng xung kích trong vật lý trị liệu", ["Thuyết giảng kết hợp hình ảnh thiết bị: đại cương; các loại sóng xung kích; thiết bị và kỹ thuật điều trị; ứng dụng; an toàn và phòng ngừa."], 30],
      ["4. Bài tập nhóm – nghiên cứu tình huống", ["Nhóm lập danh sách các bệnh được áp dụng 4 phương thức và các biện pháp an toàn tương ứng; đại diện nhóm trình bày."], 20],
      ["5. Tổng kết và Lượng giá tại lớp", ["Sơ đồ tư duy tổng hợp 4 phương thức; câu hỏi nhanh.", "Dặn dò xem lại quy trình trước buổi thực hành."], 10],
    ],
    post,
  },
  // ===================== BÀI 3 =====================
  {
    title: "Các dòng điện xung", lt: 3, part: "A",
    summary: "Bài học trình bày ba nội dung: kích thích điện thần kinh – cơ (kích thích điện, các dòng điện kích thích, kỹ thuật điều trị); chẩn đoán điện (hoạt động điện của các dây thần kinh, điện chẩn đoán); các dòng điện giảm đau (dòng siêu kích thích điện, dòng TENS, dòng Diadynamic, dòng giao thoa). Sinh viên tìm hiểu các tác dụng sinh lý, tác dụng điều trị, ứng dụng lâm sàng, cách lựa chọn dòng điện trong điều trị kích thích cơ và cách xác định vị trí đặt điện cực kích thích, làm cơ sở để thực hiện đúng kỹ thuật điều trị bằng điện cực điểm và bằng điện cực tấm.",
    prepIntro: elec,
    prep: [
      "Các khái niệm về các phương pháp điều trị bằng các dòng điện xung.",
      "Kích thích điện thần kinh – cơ: kích thích điện, các dòng điện kích thích, kỹ thuật điều trị.",
      "Chẩn đoán điện: hoạt động điện của các dây thần kinh; điện chẩn đoán.",
      "Các dòng điện giảm đau: dòng siêu kích thích điện, dòng TENS, dòng Diadynamic, dòng giao thoa.",
      "Tác dụng sinh lý, tác dụng điều trị và ứng dụng lâm sàng của các dòng điện xung.",
      "Cách lựa chọn dòng điện trong điều trị kích thích cơ; cách xác định vị trí đặt điện cực kích thích.",
    ],
    reallife: elecMind,
    think: ["Lên danh sách các bệnh được áp dụng các dòng điện kích thích và các dòng điện giảm đau.", "Khi nào sử dụng điện cực điểm, khi nào sử dụng điện cực tấm?"],
    refs: [R.CX],
    terms: "Kích thích điện thần kinh – cơ; Dòng điện kích thích; Chẩn đoán điện; Hoạt động điện của dây thần kinh; Dòng siêu kích thích điện; Dòng TENS; Dòng Diadynamic; Dòng giao thoa; Điện cực điểm; Điện cực tấm; Vị trí đặt điện cực",
    questions: [
      "Trình bày khái niệm kích thích điện và các dòng điện kích thích cơ.",
      "Trình bày hoạt động điện của các dây thần kinh và điện chẩn đoán.",
      "Trình bày các dòng điện giảm đau: dòng siêu kích thích điện, TENS, Diadynamic, giao thoa.",
      "Trình bày cách lựa chọn dòng điện trong điều trị kích thích cơ và cách xác định vị trí đặt điện cực kích thích.",
      "Phân biệt kỹ thuật điều trị bằng điện cực điểm và bằng điện cực tấm.",
    ],
    cases: [
      { text: "Một bệnh nhân giả định được chỉ định kích thích điện thần kinh – cơ tại phòng thực hành.",
        tasks: ["Trình bày cách lựa chọn dòng điện và xác định vị trí đặt điện cực kích thích.", "Trình bày các bước thực hiện kỹ thuật bằng điện cực điểm hoặc điện cực tấm theo bảng kiểm.", "Nêu cách xử trí khi bệnh nhân phản hồi cảm giác bất thường trong quá trình điều trị."] },
      { text: "Một bệnh nhân giả định được chỉ định điều trị giảm đau bằng dòng điện xung.",
        tasks: ["Kể tên các dòng điện giảm đau có thể sử dụng.", "Nêu tác dụng sinh lý, tác dụng điều trị của dòng điện được chọn."] },
    ],
    llo: [
      "Phân tích được khái niệm kích thích điện, các dòng điện kích thích thần kinh – cơ và các dòng điện giảm đau.",
      "Thực hiện đúng kỹ thuật điều trị bằng điện cực điểm và bằng điện cực tấm.",
      "Lựa chọn được dòng điện và vị trí đặt điện cực phù hợp với chỉ định và đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các kỹ thuật điều trị bằng dòng điện xung trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: elecGV,
    sv: ["Lên danh sách các bệnh được áp dụng các dòng điện xung."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở về các dòng điện dùng trong điều trị.", "Giới thiệu LLO của bài học."], 10],
      ["2. Kích thích điện thần kinh – cơ", ["Thuyết giảng tích cực (powerpoint, hình ảnh): kích thích điện; các dòng điện kích thích; kỹ thuật điều trị.", "Cách lựa chọn dòng điện trong điều trị kích thích cơ; cách xác định vị trí đặt điện cực kích thích; điện cực điểm và điện cực tấm."], 50],
      ["3. Chẩn đoán điện", ["Thuyết giảng: hoạt động điện của các dây thần kinh; điện chẩn đoán."], 25],
      ["4. Các dòng điện giảm đau", ["Thuyết giảng kết hợp phim: dòng siêu kích thích điện; dòng TENS; dòng Diadynamic; dòng giao thoa.", "Trò chơi câu trả lời tiếp sức: ghép dòng điện với tác dụng điều trị."], 45],
      ["5. Tổng kết và Lượng giá tại lớp", ["Tóm tắt bằng sơ đồ tư duy; câu hỏi nhanh.", "Dặn dò xem lại quy trình trước buổi thực hành."], 20],
    ],
    post,
  },
  // ===================== BÀI 4 =====================
  {
    title: "Máy kéo cột sống", lt: 1, part: "A",
    summary: "Bài học trình bày đại cương và phân loại máy kéo cột sống, nguyên lý hoạt động và cơ chế tác động, chỉ định và chống chỉ định của kéo cột sống, kỹ thuật điều trị, ứng dụng trong lâm sàng, an toàn và phòng ngừa. Bài học giúp sinh viên thực hiện đúng những nguyên tắc tổng quát khi điều trị kéo cột sống, thực hiện kỹ thuật điều trị bằng máy kéo cột sống và các biện pháp bảo đảm an toàn cho bệnh nhân trong quá trình điều trị.",
    prepIntro: elec,
    prep: [
      "Đại cương và phân loại máy kéo cột sống.",
      "Nguyên lý hoạt động và cơ chế tác động.",
      "Chỉ định và chống chỉ định của kéo cột sống.",
      "Những nguyên tắc tổng quát và kỹ thuật điều trị bằng máy kéo cột sống.",
      "Ứng dụng trong lâm sàng; an toàn và phòng ngừa.",
    ],
    reallife: elecMind,
    think: ["Lên danh sách các bệnh được áp dụng điều trị bằng máy kéo cột sống.", "Những biện pháp nào bảo đảm an toàn cho bệnh nhân trong quá trình kéo cột sống?"],
    refs: [R.CX],
    terms: "Máy kéo cột sống; Phân loại máy kéo; Nguyên lý hoạt động; Cơ chế tác động; Chỉ định; Chống chỉ định; An toàn và phòng ngừa",
    questions: [
      "Trình bày các loại máy kéo cột sống và nguyên lý hoạt động.",
      "Trình bày cơ chế tác động của kéo cột sống.",
      "Kể chỉ định và chống chỉ định của máy kéo cột sống.",
      "Trình bày những nguyên tắc tổng quát khi điều trị kéo cột sống.",
      "Nêu các biện pháp bảo đảm an toàn cho bệnh nhân trong quá trình điều trị.",
    ],
    cases: [
      { text: "Một bệnh nhân giả định được chỉ định điều trị bằng máy kéo cột sống tại phòng thực hành.",
        tasks: ["Liệt kê các chống chỉ định cần kiểm tra.", "Trình bày các bước thực hiện kỹ thuật theo bảng kiểm.", "Nêu các biện pháp bảo đảm an toàn cho bệnh nhân trong quá trình kéo."] },
    ],
    llo: [
      "Phân tích được các loại máy kéo cột sống, nguyên lý, chỉ định và chống chỉ định của kéo cột sống.",
      "Thực hiện đúng nguyên tắc tổng quát và kỹ thuật kéo cột sống, bảo đảm an toàn cho người bệnh.",
      "Lựa chọn được kỹ thuật kéo phù hợp với chỉ định và đáp ứng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành kỹ thuật kéo cột sống trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: elecGV,
    sv: ["Lên danh sách các bệnh được áp dụng điều trị bằng máy kéo cột sống."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở về các trường hợp được kéo cột sống.", "Giới thiệu LLO của bài học."], 5],
      ["2. Đại cương, phân loại và nguyên lý", ["Thuyết giảng tích cực (powerpoint, hình ảnh máy kéo): đại cương và phân loại; nguyên lý hoạt động và cơ chế tác động."], 15],
      ["3. Chỉ định, chống chỉ định và kỹ thuật điều trị", ["Thuyết giảng kết hợp phim: chỉ định, chống chỉ định; nguyên tắc tổng quát và kỹ thuật điều trị; ứng dụng trong lâm sàng; an toàn và phòng ngừa.", "Trò chơi trả lời nhanh: phân loại chỉ định/chống chỉ định."], 25],
      ["4. Tổng kết và Lượng giá tại lớp", ["Tóm tắt; câu hỏi nhanh.", "Dặn dò xem lại quy trình trước buổi thực hành."], 5],
    ],
    post,
  },
];

const C = [
  // ===================== BÀI 8 =====================
  {
    title: "Đại cương về kỹ thuật tạo thuận thần kinh cơ cảm thụ bản thể", lt: 1, part: "C",
    summary: "Bài học cung cấp kiến thức cơ bản về lịch sử phát triển của phương pháp tạo thuận cảm thụ bản thể thần kinh cơ (PNF), một số định nghĩa về tạo thuận, cảm thụ bản thể, thần kinh cơ, vai trò và các nguyên lý cơ bản của kỹ thuật PNF. Đây là nền tảng để sinh viên tiếp cận các mẫu chuyển động, các thao tác cơ bản và các kỹ thuật đặc hiệu ở các bài tiếp theo.",
    prepIntro: pnf,
    prep: [
      "Lịch sử phương pháp tạo thuận cảm thụ bản thể thần kinh cơ (PNF).",
      "Một số định nghĩa về: tạo thuận, cảm thụ bản thể, thần kinh cơ.",
      "Các nguyên lý cơ bản của kỹ thuật PNF.",
    ],
    reallife: "Sinh viên mô tả đặc tính của một mẫu cử động bình thường hay gặp trong cuộc sống.",
    think: ["Tìm ví dụ cụ thể để mô tả cho các định nghĩa về tạo thuận, cảm thụ bản thể, thần kinh cơ."],
    refs: [R.HO, R.LKD],
    terms: "Tạo thuận cảm thụ bản thể thần kinh cơ (PNF); Tạo thuận; Cảm thụ bản thể; Thần kinh cơ; Nguyên lý cơ bản của PNF",
    questions: [
      "Trình bày lịch sử phương pháp tạo thuận cảm thụ bản thể thần kinh cơ.",
      "Nêu một số định nghĩa về tạo thuận, cảm thụ bản thể, thần kinh cơ.",
      "Liệt kê các nguyên lý cơ bản của PNF.",
      "Mô tả đặc tính của một mẫu cử động bình thường hay gặp trong cuộc sống.",
    ],
    cases: [
      { text: "Sinh viên quan sát một hoạt động thường ngày của người thân.",
        tasks: ["Mô tả đặc tính của mẫu cử động quan sát được.", "Dùng ví dụ này để giải thích các định nghĩa tạo thuận, cảm thụ bản thể, thần kinh cơ."] },
    ],
    llo: [
      "Trình bày được lịch sử, định nghĩa và những nguyên tắc chính của kỹ thuật tạo thuận thần kinh cơ cảm thụ bản thể.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
    ],
    gv: pnfGV,
    sv: ["Tập vở, bút để ghi chép và/hoặc máy tính laptop để lưu dữ liệu."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở: “Mẫu cử động bình thường trong cuộc sống có đặc tính gì?”", "Giới thiệu LLO của bài học."], 5],
      ["2. Lịch sử phương pháp PNF", ["Thuyết giảng tích cực (powerpoint): lịch sử phương pháp tạo thuận cảm thụ bản thể thần kinh cơ."], 10],
      ["3. Các định nghĩa", ["Thuyết giảng: định nghĩa tạo thuận, cảm thụ bản thể, thần kinh cơ.", "Học nhóm: tìm ví dụ cụ thể cho từng định nghĩa."], 15],
      ["4. Các nguyên lý cơ bản của PNF", ["Thuyết giảng kết hợp hình ảnh, phim: các nguyên lý cơ bản của kỹ thuật PNF."], 12],
      ["5. Tổng kết và Lượng giá tại lớp", ["Vẽ sơ đồ tư duy tổng kết; trả lời nhanh.", "Dặn dò đọc trước bài Các mẫu chuyển động."], 8],
    ],
    post,
  },
  // ===================== BÀI 9 =====================
  {
    title: "Các mẫu chuyển động", lt: 1, part: "C",
    summary: "Bài học giới thiệu các mẫu chuyển động của PNF: sự kết hợp các mẫu chuyển động, các thành phần chuyển động, các thành phần cơ chủ yếu, đường chuyển động, hoạt động phối hợp của các cơ, các loại co cơ và chỉ định cho các mẫu. Bài học giúp sinh viên trình bày đúng các thành phần của một mẫu, phân tích hoạt động của các cơ chủ yếu và các loại co cơ trong một mẫu, từ đó thực hiện đúng các mẫu chuyển động của chi trên, chi dưới, đầu cổ và thân mình trên cơ thể người học.",
    prepIntro: pnf,
    prep: [
      "Kiến thức về mặt phẳng, cử động, thành phần cơ trong từng cử động.",
      "Sự kết hợp các mẫu chuyển động; các thành phần chuyển động.",
      "Các thành phần cơ chủ yếu; đường chuyển động; hoạt động phối hợp của các cơ.",
      "Các loại co cơ và chỉ định cho các mẫu.",
      "Các nguyên tắc thực hiện ở các trụ xoay trong từng mẫu chuyển động.",
      "Các mẫu chuyển động ở chi trên và chi dưới.",
    ],
    reallife: "Sinh viên thực hiện lại các mẫu chuyển động của chi trên, chi dưới, đầu cổ và thân mình trên chính cơ thể mình.",
    think: ["Phân biệt sự khác nhau của các loại co cơ được sử dụng và những lưu ý khi chỉ định mẫu.", "Sự kết hợp mẫu chuyển động của hai bên cơ thể diễn ra như thế nào?"],
    refs: [R.HO, R.LKD, R.ADL],
    terms: "Mẫu chuyển động; Thành phần chuyển động; Thành phần cơ chủ yếu; Đường chuyển động; Hoạt động phối hợp của các cơ; Các loại co cơ; Trụ xoay; Kết hợp mẫu chuyển động hai bên",
    questions: [
      "Trình bày các thành phần của một mẫu chuyển động.",
      "Liệt kê các mẫu chuyển động ở chi trên và chi dưới.",
      "Phân tích hoạt động của các cơ chủ yếu và hoạt động phối hợp của các cơ trong một mẫu chuyển động.",
      "Phân biệt các loại co cơ được sử dụng và những lưu ý khi chỉ định mẫu.",
      "Trình bày các nguyên tắc thực hiện ở các trụ xoay trong từng mẫu chuyển động.",
    ],
    cases: [
      { text: "Trong nhóm thực hành, một sinh viên thực hiện một mẫu chuyển động chi trên, một sinh viên khác quan sát.",
        tasks: ["Xác định các thành phần chuyển động và đường chuyển động của mẫu.", "Phân tích các cơ chủ yếu và loại co cơ tham gia.", "Nhận xét việc thực hiện ở các trụ xoay."] },
    ],
    llo: [
      "Trình bày đúng và đầy đủ các thành phần của một mẫu chuyển động.",
      "Phân tích được hoạt động của các cơ chủ yếu và các loại co cơ trong một mẫu chuyển động.",
      "Thực hiện đúng các mẫu chuyển động trên cơ thể người học.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các mẫu chuyển động của PNF trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: pnfGV,
    sv: ["Ôn tập lại kiến thức về mặt phẳng, cử động, thành phần cơ trong từng cử động."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở về mặt phẳng và cử động.", "Giới thiệu LLO của bài học."], 5],
      ["2. Giới thiệu về các mẫu chuyển động", ["Thuyết giảng tích cực (powerpoint, hình ảnh): sự kết hợp các mẫu chuyển động; các thành phần chuyển động; đường chuyển động."], 15],
      ["3. Thành phần cơ và các loại co cơ", ["Thuyết giảng kết hợp phim: các thành phần cơ chủ yếu; hoạt động phối hợp của các cơ; các loại co cơ và chỉ định cho các mẫu.", "Học nhóm: liệt kê các mẫu chuyển động ở chi trên và chi dưới."], 22],
      ["4. Tổng kết và Lượng giá tại lớp", ["Trả lời nhanh; tóm tắt.", "Dặn dò thực hiện lại các mẫu chuyển động trước buổi thực hành."], 8],
    ],
    post,
  },
  // ===================== BÀI 10 =====================
  {
    title: "Những thao tác cơ bản của kỹ thuật tạo thuận", lt: 2, part: "C",
    summary: "Bài học trình bày những thao tác cơ bản được sử dụng trong PNF: nguyên tắc chạm tay, mệnh lệnh và sự giao tiếp, sự kéo giãn, sự kéo tách và dồn khớp, đề kháng tối đa, thời điểm bình thường và sự tăng cường. Sinh viên phân tích ý nghĩa của những thao tác này khi thực hiện đồng thời với các mẫu, giải thích và ứng dụng thời điểm bình thường và thời điểm tác động trên các mẫu vận động. Đây là các thao tác được áp dụng trên các mẫu đối xứng và trong quá trình tập vận động cho bệnh nhân có tổn thương thần kinh.",
    prepIntro: pnf,
    prep: [
      "Nguyên tắc chạm tay.",
      "Mệnh lệnh và sự giao tiếp.",
      "Sự kéo giãn; sự kéo tách và dồn khớp.",
      "Đề kháng tối đa.",
      "Thời điểm bình thường; sự tăng cường.",
      "Ý nghĩa của những thao tác này khi thực hiện đồng thời với các mẫu.",
    ],
    reallife: "Sinh viên áp dụng các thao tác này lên các mẫu đối xứng và so sánh sự đáp ứng của mẫu.",
    think: ["Áp dụng các thao tác trên trong quá trình tập vận động cho bệnh nhân có tổn thương thần kinh.", "Sự đáp ứng trên cùng một mẫu khác nhau thế nào khi có và không có áp dụng các thao tác cơ bản?"],
    refs: [R.NTD],
    terms: "Nguyên tắc chạm tay; Mệnh lệnh; Giao tiếp; Kéo giãn; Kéo tách; Dồn khớp; Đề kháng tối đa; Thời điểm bình thường; Thời điểm tác động; Sự tăng cường",
    questions: [
      "Nêu những thao tác cơ bản được sử dụng trong PNF.",
      "Trình bày ý nghĩa và cách đặt tay để kích thích tạo thuận.",
      "Trình bày cách truyền đạt mệnh lệnh để người bệnh thực hiện cử động.",
      "Trình bày và phân tích ý nghĩa các kỹ thuật kéo giãn, kéo tách, dồn khớp.",
      "Giải thích thời điểm bình thường và thời điểm tác động trên các mẫu vận động.",
    ],
    cases: [
      { text: "Nhóm sinh viên thực hiện một mẫu chuyển động đã học ở bài trước trên bạn đóng vai bệnh nhân, lần lượt không áp dụng và có áp dụng các thao tác cơ bản.",
        tasks: ["Ghi nhận sự đáp ứng khác nhau trên cùng một mẫu khi có và không có áp dụng thao tác.", "Phân tích tác dụng của từng thao tác: chạm tay, mệnh lệnh, kéo giãn, kéo tách/dồn khớp, đề kháng, thời điểm.", "So sánh sự đáp ứng khi áp dụng các thao tác lên các mẫu đối xứng."] },
    ],
    llo: [
      "Trình bày được ý nghĩa và cách đặt tay để kích thích tạo thuận.",
      "Trình bày được cách truyền đạt mệnh lệnh để người bệnh thực hiện cử động.",
      "Phân tích được ý nghĩa các kỹ thuật kéo giãn, kéo tách, dồn khớp.",
      "Ứng dụng được thời điểm bình thường và thời điểm tác động trên các mẫu vận động.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp (quy định thực hành nghề nghiệp, đạo đức, giao tiếp với người bệnh) trong quá trình ra quyết định và thực hành các thao tác cơ bản của kỹ thuật tạo thuận trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: pnfGV,
    sv: ["Nêu trước những thao tác cơ bản được sử dụng trong PNF."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở: những thao tác cơ bản được sử dụng trong PNF.", "Giới thiệu LLO của bài học."], 5],
      ["2. Nguyên tắc chạm tay; mệnh lệnh và sự giao tiếp", ["Thuyết giảng tích cực (powerpoint, hình ảnh, phim): ý nghĩa và cách đặt tay; cách truyền đạt mệnh lệnh để người bệnh thực hiện cử động."], 25],
      ["3. Kéo giãn, kéo tách và dồn khớp; đề kháng tối đa", ["Thuyết giảng: ý nghĩa của sự kéo giãn, kéo tách, dồn khớp và đề kháng tối đa.", "Giảng viên minh họa trên sinh viên đóng vai."], 25],
      ["4. Thời điểm bình thường và sự tăng cường", ["Thuyết giảng: thời điểm bình thường, thời điểm tác động, sự tăng cường trên các mẫu vận động.", "Học nhóm: phân tích ý nghĩa của các thao tác khi thực hiện đồng thời với các mẫu; đại diện trình bày."], 30],
      ["5. Tổng kết và Lượng giá tại lớp", ["Trả lời nhanh; tóm tắt.", "Dặn dò chia nhóm, chuẩn bị nội dung, phân vai cho buổi thực hành."], 15],
    ],
    post,
  },
  // ===================== BÀI 11 =====================
  {
    title: "Những kỹ thuật đặc hiệu", lt: 2, part: "C",
    summary: "Bài học trình bày những kỹ thuật đặc hiệu được sử dụng trong PNF: khởi động nhịp nhàng, kết hợp co cơ đẳng trương, đảo nghịch đối kháng, kéo giãn lặp lại, co nghỉ, giữ nghỉ, sao chép và các kỹ thuật PNF và áp dụng. Sinh viên phân tích ý nghĩa của các kỹ thuật tạo thuận đặc hiệu khi thực hiện đồng thời với các mẫu và ứng dụng các kỹ thuật này trong các mẫu vận động để đạt được mục tiêu cụ thể, giải quyết các tình huống đặt ra.",
    prepIntro: pnf,
    prep: [
      "Khởi động nhịp nhàng.",
      "Kết hợp co cơ đẳng trương.",
      "Đảo nghịch đối kháng.",
      "Kéo giãn lặp lại.",
      "Co nghỉ; giữ nghỉ.",
      "Sao chép.",
      "Các kỹ thuật PNF và áp dụng.",
    ],
    reallife: "Sinh viên thực tập thường xuyên các kỹ thuật đặc hiệu và các thao tác trên từng mẫu đã học.",
    think: ["Lấy ví dụ để làm rõ tác dụng của từng kỹ thuật đặc hiệu.", "Kỹ thuật đặc hiệu nào phù hợp để giải quyết từng tình huống đặt ra?"],
    refs: [R.NTD],
    terms: "Khởi động nhịp nhàng; Kết hợp co cơ đẳng trương; Đảo nghịch đối kháng; Kéo giãn lặp lại; Co nghỉ; Giữ nghỉ; Sao chép",
    questions: [
      "Nêu những kỹ thuật đặc hiệu được sử dụng trong PNF.",
      "Trình bày ý nghĩa của từng kỹ thuật tạo thuận đặc hiệu.",
      "Phân tích ý nghĩa của các kỹ thuật đặc hiệu khi thực hiện đồng thời với các mẫu.",
      "Lấy ví dụ để làm rõ tác dụng của từng kỹ thuật.",
      "Trình bày cách ứng dụng các kỹ thuật đặc hiệu trong các mẫu vận động để đạt được mục tiêu cụ thể.",
    ],
    cases: [
      { text: "Nhóm sinh viên thực hiện một mẫu vận động đã học trên bạn đóng vai bệnh nhân và áp dụng lần lượt các kỹ thuật đặc hiệu.",
        tasks: ["Phân tích tác dụng của từng kỹ thuật tạo thuận trên mẫu đó.", "Lựa chọn kỹ thuật đặc hiệu phù hợp với mục tiêu cụ thể do giảng viên đặt ra.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."] },
    ],
    llo: [
      "Trình bày được ý nghĩa của những kỹ thuật tạo thuận đặc hiệu.",
      "Ứng dụng được các kỹ thuật đặc hiệu trong các mẫu vận động để đạt được mục tiêu cụ thể.",
      "Lựa chọn được kỹ thuật đặc hiệu phù hợp cho các hoạt động chức năng của người bệnh.",
      "Thể hiện thái độ trách nhiệm, hợp tác và tự học trong các hoạt động học tập lý thuyết của bài.",
      "Thể hiện sự chuyên nghiệp trong quá trình ra quyết định và thực hành các kỹ thuật đặc hiệu của PNF trên mô hình hoặc tình huống lâm sàng giả định.",
    ],
    gv: pnfGV,
    sv: ["Nêu trước những kỹ thuật đặc biệt được sử dụng trong PNF."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: [
      ["1. Mở đầu", ["Ổn định lớp, kiểm tra sĩ số.", "Câu hỏi mở: những kỹ thuật đặc hiệu được sử dụng trong PNF.", "Giới thiệu LLO của bài học."], 5],
      ["2. Khởi động nhịp nhàng; kết hợp co cơ đẳng trương", ["Thuyết giảng tích cực (powerpoint, phim): ý nghĩa và cách thực hiện; giảng viên minh họa trên sinh viên đóng vai."], 20],
      ["3. Đảo nghịch đối kháng; kéo giãn lặp lại", ["Thuyết giảng kết hợp phim: ý nghĩa và cách thực hiện; minh họa trên sinh viên đóng vai."], 25],
      ["4. Co nghỉ; giữ nghỉ; sao chép", ["Thuyết giảng: ý nghĩa và cách thực hiện; các kỹ thuật PNF và áp dụng.", "Nghiên cứu tình huống – học nhóm: lấy ví dụ làm rõ tác dụng của từng kỹ thuật; đại diện trình bày."], 35],
      ["5. Tổng kết và Lượng giá tại lớp", ["Trò chơi câu trả lời tiếp sức: ghép kỹ thuật với mục tiêu.", "Dặn dò chia nhóm, chuẩn bị nội dung, phân vai cho buổi thực hành."], 15],
    ],
    post,
  },
  // ===================== BÀI 12 =====================
  {
    title: "Các mẫu PNF của cổ", lt: 2, part: "C",
    summary: "Bài học giới thiệu những tiến trình cơ bản cho một mẫu vận động và áp dụng cho vùng cổ: chỉ định, mẫu gập với gập bên bên phải và xoay sang phải, mẫu duỗi với gập bên bên trái và xoay sang trái. Sinh viên xác định các điểm cần ghi nhớ khi thao tác các mẫu trên vùng cổ, áp dụng các nguyên tắc cơ bản và thao tác khi thực hiện hai mẫu cơ bản ở vùng cổ, đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai và áp dụng các mẫu vận động ở cổ cho bệnh nhân cụ thể.",
    prepIntro: pnf,
    prep: [
      "Giới thiệu và những tiến trình cơ bản cho một mẫu vận động.",
      "Chỉ định và các mục đích để tập luyện mẫu cổ.",
      "Mẫu gập với gập bên bên phải và xoay sang phải.",
      "Mẫu duỗi với gập bên bên trái và xoay sang trái.",
      "Các điểm cần ghi nhớ khi thao tác các mẫu trên vùng cổ.",
    ],
    reallife: "Sinh viên xem video về mẫu PNF cổ và đóng vai tự thực hiện kỹ thuật.",
    think: ["Áp dụng các thao tác và kỹ thuật đặc hiệu lên các mẫu còn lại của cổ.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."],
    refs: [R.NTD],
    terms: "Tiến trình cơ bản; Mẫu cổ; Gập với gập bên bên phải và xoay sang phải; Duỗi với gập bên bên trái và xoay sang trái; Chỉ định",
    questions: [
      "Liệt kê các mục đích để tập luyện mẫu cổ.",
      "Trình bày những tiến trình cơ bản của mẫu cổ.",
      "Trình bày kỹ thuật thao tác mẫu gập với gập bên bên phải và xoay sang phải.",
      "Trình bày kỹ thuật thao tác mẫu duỗi với gập bên bên trái và xoay sang trái.",
      "Nêu các điểm cần ghi nhớ khi thao tác các mẫu trên vùng cổ.",
    ],
    cases: [
      { text: "Nhóm sinh viên thực hành hai mẫu cơ bản ở vùng cổ trên bạn đóng vai bệnh nhân.",
        tasks: ["Áp dụng các nguyên tắc cơ bản và thao tác khi thực hiện hai mẫu cơ bản ở vùng cổ.", "Áp dụng các thao tác và kỹ thuật đặc hiệu lên các mẫu còn lại của cổ.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."] },
    ],
    llo: PNF_LLO("cổ"),
    gv: pnfGV,
    sv: ["Xem video về mẫu PNF cổ."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: regionActs({ open: "mục đích để tập luyện mẫu cổ là gì?", purpose: "Chỉ định và các mục đích để tập luyện mẫu cổ.", region: "cổ", patterns: "gập với gập bên bên phải và xoay sang phải; duỗi với gập bên bên trái và xoay sang trái", n: "2 mẫu cơ bản" }),
    post,
  },
  // ===================== BÀI 13 =====================
  {
    title: "Các mẫu PNF của thân", lt: 2, part: "C",
    summary: "Bài học giới thiệu những tiến trình cơ bản cho một mẫu vận động và áp dụng cho vùng thân: mẫu gập với xoay sang phải phần thân trên, duỗi với xoay sang trái phần thân trên, gập với xoay sang trái phần thân dưới, duỗi với xoay sang phải phần thân dưới. Sinh viên xác định các điểm cần ghi nhớ khi thao tác các mẫu trên vùng thân, áp dụng các nguyên tắc cơ bản và thao tác khi thực hiện bốn mẫu cơ bản ở vùng thân, đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai và áp dụng các mẫu vận động ở thân cho bệnh nhân cụ thể.",
    prepIntro: pnf,
    prep: [
      "Giới thiệu và những tiến trình cơ bản cho một mẫu vận động.",
      "Các mục đích để tập luyện mẫu thân.",
      "Gập với xoay sang phải phần thân trên; duỗi với xoay sang trái phần thân trên.",
      "Gập với xoay sang trái phần thân dưới; duỗi với xoay sang phải phần thân dưới.",
      "Các điểm cần ghi nhớ khi thao tác các mẫu trên vùng thân.",
    ],
    reallife: "Sinh viên xem video về mẫu PNF thân và đóng vai tự thực hiện kỹ thuật.",
    think: ["Áp dụng các thao tác và kỹ thuật đặc hiệu lên các mẫu còn lại của thân.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."],
    refs: [R.NTD],
    terms: "Tiến trình cơ bản; Mẫu thân; Phần thân trên; Phần thân dưới; Gập với xoay; Duỗi với xoay",
    questions: [
      "Liệt kê các mục đích để tập luyện mẫu thân.",
      "Trình bày những tiến trình cơ bản của mẫu thân.",
      "Trình bày kỹ thuật thao tác các mẫu phần thân trên.",
      "Trình bày kỹ thuật thao tác các mẫu phần thân dưới.",
      "Nêu các điểm cần ghi nhớ khi thao tác các mẫu trên vùng thân.",
    ],
    cases: [
      { text: "Nhóm sinh viên thực hành bốn mẫu cơ bản ở vùng thân trên bạn đóng vai bệnh nhân.",
        tasks: ["Áp dụng các nguyên tắc cơ bản và thao tác khi thực hiện 4 mẫu cơ bản ở vùng thân.", "Áp dụng các thao tác và kỹ thuật đặc hiệu lên các mẫu còn lại của thân.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."] },
    ],
    llo: PNF_LLO("thân"),
    gv: pnfGV,
    sv: ["Xem video về mẫu PNF thân."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: regionActs({ open: "mục đích để tập luyện mẫu thân là gì?", purpose: "Các mục đích để tập luyện mẫu thân.", region: "thân", patterns: "gập với xoay sang phải phần thân trên; duỗi với xoay sang trái phần thân trên; gập với xoay sang trái phần thân dưới; duỗi với xoay sang phải phần thân dưới", n: "4 mẫu cơ bản" }),
    post,
  },
  // ===================== BÀI 14 =====================
  {
    title: "Các mẫu PNF của chi trên", lt: 2, part: "C",
    summary: "Bài học giới thiệu những tiến trình cơ bản cho một mẫu vận động và áp dụng cho chi trên: mẫu gập dạng xoay ngoài, mẫu duỗi khép xoay trong, mẫu gập khép xoay ngoài, mẫu duỗi dạng xoay trong và tóm tắt các mẫu chuyển động chi trên. Sinh viên xác định các điểm cần ghi nhớ khi thao tác các mẫu ở chi trên, áp dụng các thao tác cơ bản và kỹ thuật đặc hiệu khi thực hiện bốn mẫu cơ bản ở chi trên, đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai và áp dụng các mẫu vận động ở chi trên cho bệnh nhân cụ thể.",
    prepIntro: pnf,
    prep: [
      "Giới thiệu và những tiến trình cơ bản cho một mẫu vận động.",
      "Các mục đích để tập luyện mẫu chi trên.",
      "Mẫu gập dạng xoay ngoài; mẫu duỗi khép xoay trong.",
      "Mẫu gập khép xoay ngoài; mẫu duỗi dạng xoay trong.",
      "Tóm tắt các mẫu chuyển động chi trên.",
      "Các điểm cần ghi nhớ khi thao tác các mẫu ở chi trên.",
    ],
    reallife: "Sinh viên xem video về mẫu PNF chi trên và đóng vai tự thực hiện kỹ thuật với bạn học trong nhóm.",
    think: ["Luyện tập các thao tác và kỹ thuật đặc hiệu lên các mẫu phối hợp của chi trên.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."],
    refs: [R.HO, R.LKD],
    terms: "Tiến trình cơ bản; Mẫu chi trên; Gập dạng xoay ngoài; Duỗi khép xoay trong; Gập khép xoay ngoài; Duỗi dạng xoay trong; Mẫu phối hợp",
    questions: [
      "Liệt kê các mục đích để tập luyện mẫu chi trên.",
      "Trình bày những tiến trình cơ bản của mẫu chi trên.",
      "Trình bày kỹ thuật thao tác mẫu gập dạng xoay ngoài và mẫu duỗi khép xoay trong.",
      "Trình bày kỹ thuật thao tác mẫu gập khép xoay ngoài và mẫu duỗi dạng xoay trong.",
      "Nêu các điểm cần ghi nhớ khi thao tác các mẫu ở chi trên.",
    ],
    cases: [
      { text: "Nhóm sinh viên thực hành bốn mẫu cơ bản ở chi trên trên bạn đóng vai bệnh nhân.",
        tasks: ["Áp dụng các thao tác cơ bản và kỹ thuật đặc hiệu khi thực hiện 4 mẫu cơ bản ở chi trên.", "Luyện tập các thao tác và kỹ thuật đặc hiệu lên các mẫu phối hợp của chi trên.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."] },
    ],
    llo: PNF_LLO("chi trên"),
    gv: pnfGV,
    sv: ["Xem video về mẫu PNF chi trên."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: regionActs({ open: "mục đích để tập luyện mẫu chi trên là gì?", purpose: "Các mục đích để tập luyện mẫu chi trên.", region: "chi trên", patterns: "gập dạng xoay ngoài; duỗi khép xoay trong; gập khép xoay ngoài; duỗi dạng xoay trong; tóm tắt các mẫu chuyển động chi trên", n: "4 mẫu cơ bản" }),
    post,
  },
  // ===================== BÀI 15 =====================
  {
    title: "Các mẫu PNF của chi dưới", lt: 2, part: "C",
    summary: "Bài học giới thiệu những tiến trình cơ bản cho một mẫu vận động và áp dụng cho chi dưới: mẫu gập dạng xoay trong, mẫu duỗi khép xoay ngoài, mẫu gập khép xoay ngoài, mẫu duỗi dạng xoay trong và tóm tắt các mẫu chuyển động chi dưới. Sinh viên xác định các điểm cần ghi nhớ khi thao tác các mẫu ở chi dưới, áp dụng các thao tác cơ bản và kỹ thuật đặc hiệu khi thực hiện bốn mẫu cơ bản ở chi dưới, đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai và áp dụng các mẫu vận động ở chi dưới cho bệnh nhân cụ thể.",
    prepIntro: pnf,
    prep: [
      "Giới thiệu và những tiến trình cơ bản cho một mẫu vận động.",
      "Các mục đích để tập luyện mẫu chi dưới.",
      "Mẫu gập dạng xoay trong; mẫu duỗi khép xoay ngoài.",
      "Mẫu gập khép xoay ngoài; mẫu duỗi dạng xoay trong.",
      "Tóm tắt các mẫu chuyển động chi dưới.",
      "Các điểm cần ghi nhớ khi thao tác các mẫu ở chi dưới.",
    ],
    reallife: "Sinh viên xem video về mẫu PNF chi dưới và đóng vai tự thực hiện kỹ thuật với bạn học trong nhóm.",
    think: ["Luyện tập các thao tác và kỹ thuật đặc hiệu lên các mẫu phối hợp của chi dưới.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."],
    refs: [R.NTD, R.HO],
    terms: "Tiến trình cơ bản; Mẫu chi dưới; Gập dạng xoay trong; Duỗi khép xoay ngoài; Gập khép xoay ngoài; Duỗi dạng xoay trong; Mẫu phối hợp",
    questions: [
      "Liệt kê các mục đích để tập luyện mẫu chi dưới.",
      "Trình bày những tiến trình cơ bản của mẫu chi dưới.",
      "Trình bày kỹ thuật thao tác mẫu gập dạng xoay trong và mẫu duỗi khép xoay ngoài.",
      "Trình bày kỹ thuật thao tác mẫu gập khép xoay ngoài và mẫu duỗi dạng xoay trong.",
      "Nêu các điểm cần ghi nhớ khi thao tác các mẫu ở chi dưới.",
    ],
    cases: [
      { text: "Nhóm sinh viên thực hành bốn mẫu cơ bản ở chi dưới trên bạn đóng vai bệnh nhân.",
        tasks: ["Áp dụng các thao tác cơ bản và kỹ thuật đặc hiệu khi thực hiện 4 mẫu cơ bản ở chi dưới.", "Luyện tập các thao tác và kỹ thuật đặc hiệu lên các mẫu phối hợp của chi dưới.", "Đánh giá hiệu quả đáp ứng trên bệnh nhân đóng vai."] },
    ],
    llo: PNF_LLO("chi dưới"),
    gv: pnfGV,
    sv: ["Xem video về mẫu PNF chi dưới."],
    materials: "Máy chiếu, bảng, phấn/bút viết, laptop, slide trình chiếu có hình ảnh, phim.",
    acts: regionActs({ open: "mục đích để tập luyện mẫu chi dưới là gì?", purpose: "Các mục đích để tập luyện mẫu chi dưới.", region: "chi dưới", patterns: "gập dạng xoay trong; duỗi khép xoay ngoài; gập khép xoay ngoài; duỗi dạng xoay trong; tóm tắt các mẫu chuyển động chi dưới", n: "4 mẫu cơ bản" }),
    post,
  },
];

module.exports = A.concat(v2.slice(4, 7), C);
